# Which target should be compiled
DEFAULT_TARGET=fb_pir_app.c

# Name of our project
# (use a single word, e.g. 'myproject')
PROJECTNAME=app-pir
PROJECT_DESCRIPTION=Pir Application

# Include global config file
-include ../Make.config
-include ../general.mk
-include ../build.mk
