# Which target should be compiled
DEFAULT_TARGET=fb_rollo_app.c

# Name of our project
# (use a single word, e.g. 'myproject')
PROJECTNAME=app-4-rollo
PROJECT_DESCRIPTION=4-Rollo Application

# Include global config file
-include ../Make.config
-include ../general.mk
-include ../build.mk
