# Use source files in folder ../app-8-out
vpath %.c ../app-8-out/

# Which target should be compiled
DEFAULT_TARGET=fb_relais_app.c

# Name of our project
# (use a single word, e.g. 'myproject')
PROJECTNAME=app-4-out
PROJECT_DESCRIPTION=4-out Application

# set it to build 4 output device
CUSTOM_CFLAGS += -DCH4

# Include global config file
-include ../Make.config
-include ../general.mk
-include ../build.mk
