# Which target should be compiled
DEFAULT_TARGET=fb_in8_app.c

# Name of our project
# (use a single word, e.g. 'myproject')
PROJECTNAME=app-8-in
PROJECT_DESCRIPTION=8-in Application

# Include global config file
-include ../Make.config
-include ../general.mk
-include ../build.mk

