# Which target should be compiled
DEFAULT_TARGET=fb_relais_app.c

# Name of our project
# (use a single word, e.g. 'myproject')
PROJECTNAME=app-8-out
PROJECT_DESCRIPTION=8-out Application

# Include global config file
-include ../Make.config
-include ../general.mk
-include ../build.mk
