FreeBusAVR: app-2-dimmer/EIB_Dimmer_2.atmega8/2-dimmer.c File Reference
app-2-dimmer/EIB_Dimmer_2.atmega8/2-dimmer.c File Reference
Dimmer mit atmega8 phasenabschnitt.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/eeprom.h>
#include <util/twi.h>
#include "uart_printf.c"
Defines
#define MAXZEIT 1000
maxzeit bis abbruch i2c
Functions
void USART_Init (void)
unsigned char TWIS_ResonseRequired (unsigned char *TWI_ResonseType)
Public Function: TWIS_ResonseRequired.
unsigned char TWIS_ReadAck (void)
Public Function: TWIS_ReadAck.
void TWIS_Stop (void)
Public Function: TWIS_Stop.
uint8_t TWIS_ReadNack (void)
Public Function: TWIS_ReadNack.
void nulldurchgang (void)
ISR (TIMER2_COMP_vect)
ISR (INT1_vect)
int main (void)
The start point of the program, init all libraries, start the bus interface, the application and check the status of the program button.
Variables
static unsigned char zl1 = 0
Timer Kanal1.
static unsigned char zl2 = 0
Timer Kanal2.
static unsigned int zl_50hz = 0
Merker für triggereingang.
static unsigned char teiler = 0
static unsigned char K1dimmwert_ausgang = 0
static unsigned char K2dimmwert_ausgang = 0
Detailed Description
Dimmer mit atmega8 phasenabschnitt.
Author:
Date:
Sun 7 9 21:30:01 2008
Define Documentation
#define MAXZEIT 1000
maxzeit bis abbruch i2c
Referenced by i2c_wait(), TWIS_ReadAck(), and TWIS_ReadNack().
Function Documentation
ISR (INT1_vect)
Todo:
add documentation
Returns:
References zl_50hz.
ISR (TIMER2_COMP_vect)
Todo:
add documentation
Returns:
References K1dimmwert_ausgang, K2dimmwert_ausgang, nulldurchgang(), teiler, zl1, zl2, and zl_50hz.
int main (void)
The start point of the program, init all libraries, start the bus interface, the application and check the status of the program button.
Returns:
References GICR, K1dimmwert_ausgang, K2dimmwert_ausgang, OCR2, TCCR2, TIMSK, TWIS_ReadAck(), TWIS_ReadNack(), TWIS_ResonseRequired(), TWIS_Stop(), and USART_Init().
void nulldurchgang (void)
Todo:
add documentation
References K1dimmwert_ausgang, K2dimmwert_ausgang, zl1, and zl2.
Referenced by ISR().
unsigned char TWIS_ReadAck (void)
Public Function: TWIS_ReadAck.
Purpose: Read a byte from the master and request next byte
Input Parameter: None
Return Value: uint8_t
uint8_t Read byte
References MAXZEIT.
Referenced by main().
uint8_t TWIS_ReadNack (void)
Public Function: TWIS_ReadNack.
Purpose: Read the last byte from the master
Input Parameter: None
Return Value: uint8_t
uint8_t Read byte
References MAXZEIT.
Referenced by main().
unsigned char TWIS_ResonseRequired (unsigned char * TWI_ResonseType)
Public Function: TWIS_ResonseRequired.
Purpose: Get the response type to be performed by slave
Input Parameter:
uint8_t* Pointer to response type on return: TWIS_ReadBytes --> Read byte(s) from master TWIS_WriteBytes --> Write byte(s) to master
Return Value: uint8_t Response required TRUE: Yes, response required FALSE: No response required
Referenced by main().
void TWIS_Stop (void)
Public Function: TWIS_Stop.
Purpose: Stop the TWI Slave Interface
Input Parameter: None
Return Value: None
Referenced by main().
void USART_Init (void)
Todo:
add documentation
Referenced by main().
Variable Documentation
unsigned char K1dimmwert_ausgang = 0 [static]
Todo:
add documentation
Referenced by ISR(), main(), and nulldurchgang().
unsigned char K2dimmwert_ausgang = 0 [static]
Todo:
add documentation
Referenced by ISR(), main(), and nulldurchgang().
unsigned char teiler = 0 [static]
Todo:
add documentation
Referenced by ISR().
unsigned char zl1 = 0 [static]
Timer Kanal1.
Referenced by ISR(), and nulldurchgang().
unsigned char zl2 = 0 [static]
Timer Kanal2.
Referenced by ISR(), and nulldurchgang().
unsigned int zl_50hz = 0 [static]
Merker für triggereingang.
Referenced by ISR().