FreeBusAVR: CMessage Class Reference
CMessage Class Reference
#include <message.h>
Public Member Functions
void SetOctet (uint8_t pos, uint16_t frame)
uint16_t GetOctet (uint8_t pos)
void Dump (uint8_t bExtended)
FRAMETYPE GetFrameType ()
uint8_t CalcChecksum (void)
uint8_t GetChecksum (void)
uint8_t IsACK (void)
uint8_t IsNAK (void)
uint8_t IsBusy (void)
Data Fields
CMessage * Next
uint8_t Len
Gesamtlänge des Telegramms.
MESSAGESTATE State
union {
uint8_t Byte [23]
struct {
union {
uint8_t Ctrl
struct {
unsigned MustZero_1:2
unsigned Priority:2
unsigned MustOne_1:1
unsigned RepeatFlag:1
unsigned MustZero_2:1
unsigned FrameType: 1
} packed
}
union {
uint16_t Value
struct {
unsigned Line:4
unsigned Range:4
uint8_t Subscriber
} packed
} Source
union {
uint16_t Value
struct {
unsigned Line:4
unsigned Range:4
unsigned Subscriber:8
} packed
struct {
unsigned Middlegroup:3
unsigned Maingroup:4
uint8_t Subgroup
} packed
} Destination
union {
uint8_t DRL
struct {
unsigned Length:4
unsigned NCF:3
unsigned DAF:1
} packed
}
uint8_t Data [17]
} L_Data
} packed
Detailed Description
Todo:
add documentation
Member Function Documentation
uint8_t CMessage::CalcChecksum (void)
Todo:
add documentation
References checksum, and Len.
Referenced by Dump().
void CMessage::Dump (uint8_t bExtended)
Todo:
add documentation
References CalcChecksum(), GetFrameType(), IsACK(), IsBusy(), IsNAK(), and Len.
Referenced by CApplication::Execute().
uint8_t CMessage::GetChecksum (void)
Todo:
add documentation
References Len.
FRAMETYPE CMessage::GetFrameType (void)
Todo:
add documentation
Referenced by Dump().
uint16_t CMessage::GetOctet (uint8_t pos)
Todo:
add documentation
uint8_t CMessage::IsACK (void)
Todo:
add documentation
Referenced by Dump().
uint8_t CMessage::IsBusy (void)
Todo:
add documentation
Referenced by Dump().
uint8_t CMessage::IsNAK (void)
Todo:
add documentation
Referenced by Dump().
void CMessage::SetOctet (uint8_t pos, uint16_t frame)
Todo:
add documentation
Field Documentation
uint8_t CMessage::Len
Gesamtlänge des Telegramms.
Referenced by CalcChecksum(), Dump(), and GetChecksum().
CMessage* CMessage::Next
Todo:
add documentation
Referenced by CApplication::Execute().
union { ... } CMessage::packed
Todo:
add documentation
MESSAGESTATE CMessage::State
Todo:
add documentation
Referenced by CApplication::Execute().
The documentation for this class was generated from the following files:
Sniffer mit USB/message.h
Sniffer mit USB/message.c