FreeBusAVR: lib/fb_eeprom.c File Reference
lib/fb_eeprom.c File Reference
The eeprom is divided into two parts. The complete size of the eeprom is 256+18+24 Byte (0x0000-0x0128).
0x0000-0x00FF: Address space for parameters and addresses of the controller/application (0x0100-0x01FF)
0x0100-0x0111: User memory (0x00CE-0x00DF), 18 Byte
0x0112-0x0129: Application memory (0x0000-0x0017), 24 Byte
Handles communication from and to eeprom.
#include "fb.h"
#include "fb_hardware.h"
#include "msg_queue.h"
#include "fb_hal.h"
#include "freebus-debug.h"
#include "fb_eeprom.h"
Data Structures
struct eeprom_cmds
Data will be written to the eeprom byte by byte that structure save data and variables needed to write data to the eeprom.
Typedefs
typedef struct eeprom_cmds EEPROM_CMDS
Data will be written to the eeprom byte by byte that structure save data and variables needed to write data to the eeprom.
Functions
static void prog_ee (uint16_t addr, uint8_t dat)
Store on byte on eeprom.
static void trigger_eeprom (void)
Start to write the first byte to eeprom.
void write_memory_p (uint16_t addr, uint8_t dat)
Write directly to the eeprom, don't use the eeprom cache.
ISR (EE_RDY_vect)
Interrupt handler to write queued eeprom data byte for byte to eeprom without blocking the controller.
uint8_t eeprom_ParamRead (uint16_t addr)
Read data from the eeprom cache and return it.
void eeprom_ParamWrite (uint16_t addr, uint8_t len, uint8_t *dat)
Write data to the eeprom cache and trigger background process to write eeprom cache to real eeprom.
uint8_t eeprom_busy (void)
Check if eeprom cache was written completely to eeprom.
void eeprom_ParamSetDefault (const STRUCT_DEFPARAM *pParam)
store the default parameter directly to the eeprom
void eeprom_Init (uint8_t *nodeParam, uint16_t paramlen)
Read the eeprom to the eeprom cache.
void eeprom_print (void)
Print the complete eeprom to DEBUG defined.
Variables
uint8_t * eeprom_NodeParam
parameter structure (pointer)
uint16_t eeprom_NodeParamLen
length of the paramater structure
static struct msg * eeprom_msg
EEprom msg queue.
Detailed Description
The eeprom is divided into two parts. The complete size of the eeprom is 256+18+24 Byte (0x0000-0x0128).
0x0000-0x00FF: Address space for parameters and addresses of the controller/application (0x0100-0x01FF)
0x0100-0x0111: User memory (0x00CE-0x00DF), 18 Byte
0x0112-0x0129: Application memory (0x0000-0x0017), 24 Byte
Handles communication from and to eeprom.
Author:
Dirk Opfer, Matthias Fechner, Christian Bode
Date:
Fri Oct 26 17:18:15 2007
attention: don't use prog_ee() with opt-level 0
Typedef Documentation
typedef struct eeprom_cmds EEPROM_CMDS
Data will be written to the eeprom byte by byte that structure save data and variables needed to write data to the eeprom.
Function Documentation
uint8_t eeprom_busy (void)
Check if eeprom cache was written completely to eeprom.
Returns:
TRUE if eeprom cache is not written completely to eeprom
Todo:
???:
References FALSE, MSG_FREE, msg::state, and TRUE.
Referenced by A_Restart().
void eeprom_Init (uint8_t * nodeParam, uint16_t paramlen)
Read the eeprom to the eeprom cache.
Parameters:
nodeParam
paramlen
References eeprom_NodeParam, and eeprom_NodeParamLen.
Referenced by main().
uint8_t eeprom_ParamRead (uint16_t addr)
Read data from the eeprom cache and return it.
Parameters:
addr The address from the eeprom to read the data
Returns:
Value in eeprom on addr
References APPLICATION_MEM_BASE_ADR, APPLICATION_MEM_SIZE, BASE_ADDRESS_OFFSET, eeprom_NodeParam, NODEPARAM_SIZE, systemState, SYSTEMSTATE, USERRAM_BASE_ADR, and USERRAM_SIZE.
Referenced by A_ADC_Read(), A_GroupValue_Read(), A_GroupValue_Write(), A_Memory_Read(), fbprot_Init(), findRespondGroupAddressByObjectNumber(), getPortFunction(), PortFunc_Jalousie(), PortFunc_Switch(), read_grp_addr(), readApplication(), restartApplication(), runApplication(), sendExtTelegram(), sendTelegram(), sendTestTelegram(), switchObjects(), and timerOverflowFunction().
void eeprom_ParamSetDefault (const STRUCT_DEFPARAM * pParam)
store the default parameter directly to the eeprom
Parameters:
pParam
References eeprom_cmds::addr, BASE_ADDRESS_OFFSET, eeprom_NodeParam, eeprom_NodeParamLen, MAX_EEPROM_SIZE, NODEPARAM_SIZE, and prog_ee().
Referenced by fbprot_Init().
void eeprom_ParamWrite (uint16_t addr, uint8_t len, uint8_t * dat)
Write data to the eeprom cache and trigger background process to write eeprom cache to real eeprom.
Parameters:
addr start address of the data in the eeprom
len length of data
dat data to write in the eeprom
References eeprom_cmds::addr, AllocMsg(), APPLICATION_MEM_BASE_ADR, APPLICATION_MEM_SIZE, BASE_ADDRESS_OFFSET, eeprom_cmds::count, eeprom_cmds::data, msg::data, eeprom_NodeParam, NODEPARAM_SIZE, eeprom_cmds::offset, queuemsg(), systemState, SYSTEMSTATE, trigger_eeprom(), USERRAM_BASE_ADR, and USERRAM_SIZE.
Referenced by A_Memory_Write(), A_PhysicalAddress_Write(), and switchObjects().
void eeprom_print (void)
Print the complete eeprom to DEBUG defined.
References eeprom_cmds::addr, DEBUG_NEWLINE_BLOCKING, DEBUG_PUTC_BLOCKING, DEBUG_PUTHEX_BLOCKING, and eeprom_NodeParam.
Referenced by fbprot_Init().
ISR (EE_RDY_vect)
Interrupt handler to write queued eeprom data byte for byte to eeprom without blocking the controller.
Returns:
Todo:
ist noch unsauber
References eeprom_cmds::addr, eeprom_cmds::count, eeprom_cmds::data, msg::data, dequeuemsg(), eeprom_cmds::offset, and prog_ee().
static void prog_ee (uint16_t addr, uint8_t dat) [static]
Store on byte on eeprom.
Parameters:
addr Adress in eeprom to save data
dat Data to store
Referenced by eeprom_ParamSetDefault(), ISR(), trigger_eeprom(), and write_memory_p().
static void trigger_eeprom (void) [inline, static]
Start to write the first byte to eeprom.
The rest of the data is written to the eeprom with the ISR EE_RDY_vect.
Todo:
Aenderung ist binaercompatibel
Todo:
compare with revision 1049. if eeprom_msg is NULL that if case will fail
Bug:
if case will fail when eeprom_msg is NULL (the case when no message is queued) compare with revision 1049
References eeprom_cmds::addr, eeprom_cmds::data, msg::data, MSG_ALLOC, MSG_SENDING, eeprom_cmds::offset, prog_ee(), and msg::state.
Referenced by eeprom_ParamWrite().
void write_memory_p (uint16_t addr, uint8_t dat)
Write directly to the eeprom, don't use the eeprom cache.
Todo:
Funktion write_memory_p() duch eeprom_ParamSetDefault() ersetzen
You have to call eeprom_init() to sync eeprom cache to eeprom data. In normal situation you should use write_eeprom_block instead!
Parameters:
addr
dat
References prog_ee().
Referenced by setApplicationDefaults().
Variable Documentation
struct msg* eeprom_msg [static]
EEprom msg queue.
uint8_t* eeprom_NodeParam
parameter structure (pointer)
Referenced by eeprom_Init(), eeprom_ParamRead(), eeprom_ParamSetDefault(), eeprom_ParamWrite(), and eeprom_print().
uint16_t eeprom_NodeParamLen
length of the paramater structure
Referenced by eeprom_Init(), and eeprom_ParamSetDefault().