FreeBusAVR: include/fb_app.h File Reference
include/fb_app.h File Reference
General application definition file.
#include "msg_queue.h"
Defines
#define FBAPP_EXT extern
Set FBAPP_EXT to extern to make clear it is include from an external source like a lib.
Functions
FBAPP_EXT uint8_t restartApplication (void)
Function is called when microcontroller gets power or if the application must be restarted.
FBAPP_EXT uint8_t readApplication (struct msg *rxmsg)
Read status from port and return it.
FBAPP_EXT uint8_t runApplication (struct msg *rxmsg)
Function is called if A_GroupValue_Write is received it is the function "EIS1" or "Data Type Boolean" for the relais module.
Detailed Description
General application definition file.
Author:
Matthias Fechner
Date:
Mon Oct 13 23:53:50 2008
Define Documentation
#define FBAPP_EXT extern
Set FBAPP_EXT to extern to make clear it is include from an external source like a lib.
Function Documentation
FBAPP_EXT uint8_t readApplication (struct msg * rxmsg)
Read status from port and return it.
Parameters:
rxmsg
Returns:
Todo:
lesen des 1byte wert
Todo:
write part additional functions
Todo:
lesen des 1byte wert
Todo:
write part additional functions
Todo:
check if read value is allowed
Todo:
declaration hides hdr line 268
Todo:
write part additional functions
References AllocMsgI(), fbus_hdr::apci, ASSOCTABPTR, BASE_ADDRESS_OFFSET, fbus_hdr::ctrl, msg::data, DEBUG_PUTS, fbus_hdr::dest, eeprom_ParamRead(), FB_ACK, fb_hal_txqueue_msg(), FB_NACK, grp_addr_s::ga, grp_addr, K1dimmwert_ausgang, K2dimmwert_ausgang, msg::len, fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, portValue, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
Referenced by A_GroupValue_Read().
FBAPP_EXT uint8_t restartApplication (void)
Function is called when microcontroller gets power or if the application must be restarted.
It restores data like in the parameters defined.
Returns:
FB_ACK or FB_NACK
Todo:
add documentation
It restores data like in the parameters defined.
Returns:
It restores data like in the parameters defined.
Returns:
FB_ACK or FB_NACK
References anspringen_k1, anspringen_k2, currentTime, currentTimeOverflow, eeprom_ParamRead(), einschathellikeit_k1, einschathellikeit_k2, ENABLE_PWM, hellikeit, IO_INPUT, IO_OUTPUT, K1dimmwert, MAXDIMMWERT, mindimmwert_k1, mindimmwert_k2, OBJ_SIZE, portValue, powerOnDelay, POWERONDELAY_BASE, POWERONDELAY_FACTOR, PWM_SETPOINT, RELOAD_APPLICATION_TIMER, INTVAL_UNION::Schalten, switchObjects(), timerRunning, and waitToPWM.
Referenced by main().
FBAPP_EXT uint8_t runApplication (struct msg * rxmsg)
Function is called if A_GroupValue_Write is received it is the function "EIS1" or "Data Type Boolean" for the relais module.
Read all parameters in that function and set global variables.
Parameters:
rxmsg
Returns:
Function is called if A_GroupValue_Write is received it is the function "EIS1" or "Data Type Boolean" for the relais module.
The type it is the function "EIS1" or "Data Type Boolean" for the relais module. Read all parameters in that function and set global variables.
Parameters:
rxmsg
Returns:
The return value defies if a ACK or a NACK should be sent (FB_ACK, FB_NACK)
Todo:
handle data with more then 6 bit
Todo:
write part additional functions
Todo:
handle data with more then 6 bit
Todo:
write part additional functions
Todo:
handle data with more then 6 bit
Todo:
check if object is blocked and/or write is enabled
Todo:
check how to handle switch off if timer is currently active (0x01EB)
check for delays
Todo:
write part additional functions
References fbus_hdr::apci, ASSOCTABPTR, BASE_ADDRESS_OFFSET, COMMSTAB_ADDRESS, currentTime, msg::data, DEBUG_NEWLINE, DEBUG_PUTC, DEBUG_PUTHEX, DEBUG_PUTS, DEBUG_SPACE, delayValues, fbus_hdr::dest, eeprom_ParamRead(), einschathellikeit_k1, einschathellikeit_k2, FB_ACK, FB_NACK, grp_addr_s::ga, gK1helldunkel, gK2helldunkel, grp_addr, hellikeit, K1dimmwert, K2dimmwert, msg::len, portValue, RESET_RELOAD_APPLICATION_TIMER, switchObjects(), and timerRunning.
Referenced by A_GroupValue_Write().