FreeBusAVR: include/fb_eeprom.h File Reference
include/fb_eeprom.h File Reference
Handling the access and mapping to the eeprom.
Data Structures
struct STRUCT_DEFPARAM
Struktur fuer die Default-Parameter.
Defines
#define EEPROM_EXT extern
Set EEPROM_EXT to extern to make clear it is include from an external source like a lib.
#define BASE_ADDRESS_OFFSET 0x0100
Speichergroesse des EEPROMs.
#define NODEPARAM_SIZE 0x00FF
Size of parameter structur.
#define APPLICATION_MEM_BASE_ADR 0x0000
application memory startaddress
#define APPLICATION_MEM_SIZE 0x0017
Size of application memory.
#define SYSTEMSTATE 0x0060
System Status.
#define USERRAM_BASE_ADR 0x00CE
User RAM startaddress.
#define USERRAM_SIZE 0x0012
Size of user RAM.
#define EEPROM_SIZE NODEPARAM_SIZE + APPLICATION_MEM_SIZE + USERRAM_SIZE
Size of data structur.
#define MAX_EEPROM_SIZE EEPROM_SIZE - 1
The maximum size of the eeprom usable.
Functions
EEPROM_EXT uint8_t mem_ReadByte (uint16_t wAdr)
Read data from the eeprom cache and return it.
EEPROM_EXT void mem_WriteBlock (uint16_t addr, uint8_t len, uint8_t *dat)
Write data to the eeprom cache and trigger background process to write eeprom cache to real eeprom.
EEPROM_EXT uint8_t eeprom_busy (void)
Check if eeprom cache was written completely to eeprom.
EEPROM_EXT void eeprom_ParamSetDefault (const STRUCT_DEFPARAM *pParam)
store the default parameter directly to the eeprom
EEPROM_EXT void eeprom_Init (uint8_t *pNodeParam, uint16_t wParamlen)
Read the eeprom to the eeprom cache.
EEPROM_EXT uint8_t * eeprom_GetBase (void)
Returns the pointer to the eeprom cache.
void eeprom_print (void)
Print the complete eeprom to DEBUG defined.
Detailed Description
Handling the access and mapping to the eeprom.
Author:
Dirk Opfer, Matthias Fechner, Christian Bode
Date:
Sat Apr 05 23:37:24 2008
Define Documentation
#define APPLICATION_MEM_BASE_ADR 0x0000
application memory startaddress
#define APPLICATION_MEM_SIZE 0x0017
Size of application memory.
#define BASE_ADDRESS_OFFSET 0x0100
Speichergroesse des EEPROMs.
Offset in BCU1 EEPROM
Referenced by A_PhysicalAddress_Write(), eeprom_ParamSetDefault(), find_ga(), findRespondGroupAddressByObjectNumber(), mem_ReadByte(), mem_WriteBlock(), processOutputs(), read_obj_type(), readApplication(), and runApplication().
#define EEPROM_EXT extern
Set EEPROM_EXT to extern to make clear it is include from an external source like a lib.
#define EEPROM_SIZE NODEPARAM_SIZE + APPLICATION_MEM_SIZE + USERRAM_SIZE
Size of data structur.
Referenced by main().
#define MAX_EEPROM_SIZE EEPROM_SIZE - 1
The maximum size of the eeprom usable.
Referenced by eeprom_ParamSetDefault().
#define NODEPARAM_SIZE 0x00FF
Size of parameter structur.
Referenced by A_PhysicalAddress_Write(), eeprom_ParamSetDefault(), mem_ReadByte(), and mem_WriteBlock().
#define SYSTEMSTATE 0x0060
System Status.
Referenced by mem_ReadByte(), and mem_WriteBlock().
#define USERRAM_BASE_ADR 0x00CE
User RAM startaddress.
Referenced by mem_ReadByte(), and mem_WriteBlock().
#define USERRAM_SIZE 0x0012
Size of user RAM.
Referenced by mem_ReadByte(), and mem_WriteBlock().
Function Documentation
EEPROM_EXT uint8_t eeprom_busy (void)
Check if eeprom cache was written completely to eeprom.
Returns:
TRUE if eeprom cache is not written completely to eeprom
References DEBUG_NEWLINE, DEBUG_PUTC, FALSE, and TRUE.
Referenced by A_Restart().
EEPROM_EXT uint8_t* eeprom_GetBase (void)
Returns the pointer to the eeprom cache.
This can be used for an optimized read access.
References eeprom_NodeParam.
EEPROM_EXT void eeprom_Init (uint8_t * nodeParam, uint16_t paramlen)
Read the eeprom to the eeprom cache.
Parameters:
nodeParam
paramlen
References CONFIG_EEPROM, eeprom_NodeParam, eeprom_NodeParamLen, and nodeParam.
Referenced by main().
EEPROM_EXT void eeprom_ParamSetDefault (const STRUCT_DEFPARAM * pParam)
store the default parameter directly to the eeprom
Parameters:
pParam
References eeprom_cmds::addr, BASE_ADDRESS_OFFSET, eeprom_NodeParam, eeprom_NodeParamLen, MAX_EEPROM_SIZE, and NODEPARAM_SIZE.
Referenced by fbprot_Init().
void eeprom_print (void)
Print the complete eeprom to DEBUG defined.
References eeprom_cmds::addr, DEBUG_NEWLINE_BLOCKING, DEBUG_PUTC_BLOCKING, DEBUG_PUTHEX_BLOCKING, and mem_ReadByte().
Referenced by fbprot_Init().
EEPROM_EXT uint8_t mem_ReadByte (uint16_t addr)
Read data from the eeprom cache and return it.
Parameters:
addr The address from the eeprom to read the data
Returns:
Value in eeprom on addr
References eeprom_cmds::addr, BASE_ADDRESS_OFFSET, eeprom_NodeParam, NODEPARAM_SIZE, systemState, SYSTEMSTATE, USERRAM_BASE_ADR, and USERRAM_SIZE.
Referenced by A_GroupValue_Read(), A_GroupValue_Write(), A_Memory_Read(), eeprom_print(), fbprot_Init(), find_ga(), findRespondGroupAddressByObjectNumber(), getPortFunction(), grenzwert(), messwert(), PortFunc_Jalousie(), PortFunc_Switch(), processOutputs(), read_grp_addr(), read_obj_type(), readApplication(), restartApplication(), runApplication(), send_value(), sendewert(), sendExtTelegram(), sendTelegram(), switchObjects(), and timerOverflowFunction().
EEPROM_EXT void mem_WriteBlock (uint16_t addr, uint8_t len, uint8_t * dat)
Write data to the eeprom cache and trigger background process to write eeprom cache to real eeprom.
Parameters:
addr start address of the data in the eeprom
len length of data
dat data to write in the eeprom
References eeprom_cmds::addr, AllocMsg(), BASE_ADDRESS_OFFSET, eeprom_cmds::count, eeprom_cmds::data, msg::data, eeprom_NodeParam, NODEPARAM_SIZE, eeprom_cmds::offset, queuemsg(), systemState, SYSTEMSTATE, trigger_eeprom(), USERRAM_BASE_ADR, and USERRAM_SIZE.
Referenced by A_Memory_Write(), A_PhysicalAddress_Write(), and switchObjects().