FreeBusAVR: app-8-in/fb_in8_app.c File Reference
app-8-in/fb_in8_app.c File Reference
The application for 8 binary inputs Manufactorer code is 0x04 = Jung
Device type (2118) 0x???? Ordernumber: 2118.??REG
.
#include "fb.h"
#include "fb_hardware.h"
#include "freebus-debug.h"
#include "fb_eeprom.h"
#include "msg_queue.h"
#include "fb_hal.h"
#include "fb_prot.h"
#include "fb_app.h"
#include "fb_in8_app.h"
Data Structures
union INTVAL_UNION
Defines
#define RESET_RELOAD_APPLICATION_TIMER()
Reset the internal variables used for the application timer and reload the timer itself.
#define PORTFUNCTION_12 0x01CE
#define PORTFUNCTION_34 0x01CF
#define PORTFUNCTION_56 0x01D0
#define PORTFUNCTION_78 0x01D1
#define DEBOUNCE_FACTOR 0x01D2
#define POWERONDELAY_FACTOR 0x01D4
#define PORTFUNC_BASEADR 0x01D5
#define PORTFUNC_EDGEFUNC 0x01D7
#define PORTFUNC_T1_FAKTOR 0x01D6
#define PORTFUNC_T2_FAKTOR 0x01D7
#define PORTFUNC_JALOMODE 0x01D8
#define PORTFUNC_T1_BASIS 0x01F6
#define PORTFUNC_T2_BASIS 0x01FA
#define POWERONDELAY_BASE 0x01FE
#define OBJ_SIZE 8
Enumerations
enum EFUNC_PORT {
eFunc_none, eFunc_schalten, eFunc_dimmen, eFunc_jalousie,
eFunc_dimmwertgeber, eFunc_Lichtszene, eFunc_Wertgeber, eFunc_Temperaturwertgeber,
eFunc_Helligkeitswertgeber, eFunc_Impulszaehler, eFunc_Schaltzaehler
}
Functions
void timerOverflowFunction (void)
Timer1 is used as application timer.
EFUNC_PORT getPortFunction (uint8_t port)
Get the function code for the select port.
uint8_t ReadPorts ()
Read all inputpins and store values into a byte.
void PortFunc_Switch (uint8_t port, uint8_t newPortValue, uint8_t portChanged)
Port Function: switch.
void PortFunc_Jalousie (uint8_t port, uint8_t newPortValue, uint8_t portChanged)
Port Function: Jalousie.
ISR (TIMER1_COMPB_vect)
ISR is called if on TIMER1 the comparator B matches the defined condition.
uint8_t restartApplication (void)
Function is called when microcontroller gets power or if the application must be restarted.
uint8_t readApplication (struct msg *rxmsg)
Read status from port and return it.
uint8_t runApplication (struct msg *rxmsg)
Function is called if A_GroupValue_Write is received.
int main (void)
The start point of the program, init all libraries, start the bus interface, the application and check the status of the program button.
Variables
struct grp_addr_s grp_addr
List of saved group addresses for this controller, see struct grp_addr_s for more information.
static uint8_t portValue
defines the port status.
INTVAL_UNION intVal [OBJ_SIZE]
static uint16_t currentTime
defines the current time in 10ms steps (2=20ms)
static uint8_t currentTimeOverflow
the amount of overflows from currentTime
static uint8_t currentTimeOverflowBuffer
is set to one if overflow happened, is 0 if overflow was processed
static uint8_t powerOnDelay
uint8_t nodeParam [EEPROM_SIZE]
parameterstructure (RAM)
const STRUCT_DEFPARAM
defaultParam[] PROGMEM
list of the default parameter for this application
Detailed Description
The application for 8 binary inputs Manufactorer code is 0x04 = Jung
Device type (2118) 0x???? Ordernumber: 2118.??REG
.
Author:
Matthias Fechner, Christian Bode
Date:
Sat Jan 05 17:44:47 2008
Define Documentation
#define DEBOUNCE_FACTOR 0x01D2
Todo:
add documentation
Referenced by timerOverflowFunction().
#define OBJ_SIZE 8
Todo:
add documentation
Referenced by restartApplication().
#define PORTFUNC_BASEADR 0x01D5
Todo:
add documentation
Referenced by timerOverflowFunction().
#define PORTFUNC_EDGEFUNC 0x01D7
Todo:
add documentation
Referenced by PortFunc_Switch().
#define PORTFUNC_JALOMODE 0x01D8
Todo:
add documentation
Referenced by PortFunc_Jalousie().
#define PORTFUNC_T1_BASIS 0x01F6
Todo:
add documentation
Referenced by PortFunc_Jalousie().
#define PORTFUNC_T1_FAKTOR 0x01D6
Todo:
add documentation
Referenced by PortFunc_Jalousie().
#define PORTFUNC_T2_BASIS 0x01FA
Todo:
add documentation
Referenced by PortFunc_Jalousie().
#define PORTFUNC_T2_FAKTOR 0x01D7
Todo:
add documentation
Referenced by PortFunc_Jalousie().
#define PORTFUNCTION_12 0x01CE
Todo:
add documentation
Referenced by getPortFunction().
#define PORTFUNCTION_34 0x01CF
Todo:
add documentation
Referenced by getPortFunction().
#define PORTFUNCTION_56 0x01D0
Todo:
add documentation
Referenced by getPortFunction().
#define PORTFUNCTION_78 0x01D1
Todo:
add documentation
Referenced by getPortFunction().
#define POWERONDELAY_BASE 0x01FE
Todo:
add documentation
Referenced by restartApplication().
#define POWERONDELAY_FACTOR 0x01D4
Todo:
add documentation
Referenced by restartApplication().
#define RESET_RELOAD_APPLICATION_TIMER ()
Value:
{                              \
          currentTimeOverflow=0;                                        \
          currentTimeOverflowBuffer=0;                                  \
          currentTime=0;                                                \
          RELOAD_APPLICATION_TIMER();                                   \
     }
Reset the internal variables used for the application timer and reload the timer itself.
Todo:
check if move of currentTime to this function really does not introduce a bug
Enumeration Type Documentation
enum EFUNC_PORT
Todo:
add documentation
Enumerator:
eFunc_none
Todo:
add documentation
eFunc_schalten
Todo:
add documentation
eFunc_dimmen
Todo:
add documentation
eFunc_jalousie
Todo:
add documentation
eFunc_dimmwertgeber
Todo:
add documentation
eFunc_Lichtszene
Todo:
add documentation
eFunc_Wertgeber
Todo:
add documentation
eFunc_Temperaturwertgeber
Todo:
add documentation
eFunc_Helligkeitswertgeber
Todo:
add documentation
eFunc_Impulszaehler
Todo:
add documentation
eFunc_Schaltzaehler
Todo:
add documentation
Function Documentation
EFUNC_PORT getPortFunction (uint8_t port)
Get the function code for the select port.
Returns:
port function
References eeprom_ParamRead(), PORTFUNCTION_12, PORTFUNCTION_34, PORTFUNCTION_56, and PORTFUNCTION_78.
Referenced by timerOverflowFunction().
ISR (TIMER1_COMPB_vect)
ISR is called if on TIMER1 the comparator B matches the defined condition.
int main (void)
The start point of the program, init all libraries, start the bus interface, the application and check the status of the program button.
Returns:
Todo:
Funktion fuer CRC-Check bei PowerOn fehlt noch
References CLEAR_TIMER1_OVERRUN, DISABLE_WATCHDOG, eeprom_Init(), EEPROM_SIZE, ENABLE_ALL_INTERRUPTS, fbhal_checkProgTaster(), fbhal_Init(), fbprot_Init(), msg_queue_init(), nodeParam, restartApplication(), sendTestTelegram(), TIMER1_OVERRUN, and timerOverflowFunction().
void PortFunc_Jalousie (uint8_t port, uint8_t newPortValue, uint8_t portChanged)
Port Function: Jalousie.
Parameters:
port
newPortValue
portChanged
References eeprom_ParamRead(), INTVAL_UNION::Jalousie, PORTFUNC_JALOMODE, PORTFUNC_T1_BASIS, PORTFUNC_T1_FAKTOR, PORTFUNC_T2_BASIS, PORTFUNC_T2_FAKTOR, and sendTelegram().
Referenced by timerOverflowFunction().
void PortFunc_Switch (uint8_t port, uint8_t newPortValue, uint8_t portChanged)
Port Function: switch.
Parameters:
port
newPortValue
portChanged
References eeprom_ParamRead(), PORTFUNC_EDGEFUNC, INTVAL_UNION::Schalten, and sendTelegram().
Referenced by timerOverflowFunction().
uint8_t readApplication (struct msg * rxmsg)
Read status from port and return it.
Parameters:
rxmsg
Returns:
Todo:
lesen des 1byte wert
Todo:
write part additional functions
References FB_ACK.
uint8_t ReadPorts ()
Read all inputpins and store values into a byte.
Returns:
port
Referenced by timerOverflowFunction().
uint8_t restartApplication (void)
Function is called when microcontroller gets power or if the application must be restarted.
It restores data like in the parameters defined.
Returns:
References currentTime, currentTimeOverflow, eeprom_ParamRead(), IO_INPUT, IO_OUTPUT, OBJ_SIZE, portValue, powerOnDelay, POWERONDELAY_BASE, POWERONDELAY_FACTOR, RELOAD_APPLICATION_TIMER, and INTVAL_UNION::Schalten.
uint8_t runApplication (struct msg * rxmsg)
Function is called if A_GroupValue_Write is received.
Function is called if A_GroupValue_Write is received it is the function "EIS1" or "Data Type Boolean" for the relais module.
The type it is the function "EIS1" or "Data Type Boolean" for the relais module. Read all parameters in that function and set global variables.
Parameters:
rxmsg
Returns:
The return value defies if a ACK or a NACK should be sent (FB_ACK, FB_NACK)
Todo:
handle data with more then 6 bit
Todo:
write part additional functions
References FB_NACK.
void timerOverflowFunction (void)
Timer1 is used as application timer.
It increase the variable currentTime every 130ms and currentTimeOverflow if currentTime runs over 16-bit.
Returns:
References APPLICATION_RUN_STATUS, currentTime, currentTimeOverflow, DEBOUNCE_FACTOR, eeprom_ParamRead(), eFunc_dimmen, eFunc_jalousie, eFunc_schalten, getPortFunction(), PORTFUNC_BASEADR, PortFunc_Jalousie(), PortFunc_Switch(), portValue, powerOnDelay, ReadPorts(), and sendTelegram().
Variable Documentation
uint16_t currentTime [static]
defines the current time in 10ms steps (2=20ms)
uint8_t currentTimeOverflow [static]
the amount of overflows from currentTime
Referenced by restartApplication(), and timerOverflowFunction().
uint8_t currentTimeOverflowBuffer [static]
is set to one if overflow happened, is 0 if overflow was processed
struct grp_addr_s grp_addr
List of saved group addresses for this controller, see struct grp_addr_s for more information.
INTVAL_UNION intVal[OBJ_SIZE]
Todo:
add documentation
uint8_t nodeParam[EEPROM_SIZE]
parameterstructure (RAM)
Referenced by main().
uint8_t portValue [static]
defines the port status.
LSB IO0 and MSB IO8, ports with delay can be set to 1 here but will be switched delayed depending on the delay
Referenced by restartApplication(), and timerOverflowFunction().
uint8_t powerOnDelay [static]
Todo:
add documentation
Referenced by restartApplication(), and timerOverflowFunction().
const STRUCT_DEFPARAM defaultParam [] PROGMEM
Initial value:
{
    { MANUFACTORER_ADR,        0x04 },
    { DEVICE_NUMBER_HIGH,      0x70 },
    { DEVICE_NUMBER_LOW,       0x54 },
    { SOFTWARE_VERSION_NUMBER, 0x02 },
    { APPLICATION_RUN_STATUS,  0xFF },
    { COMMSTAB_ADDRESS,        0x84 },
    { APPLICATION_PROGRAMM,    0x00 },
    { PA_ADDRESS_HIGH,         0x11 },
    { PA_ADDRESS_LOW,          0x34 },
    { 0xFF,                    0xFF }
}
list of the default parameter for this application