FreeBusAVR: include/fb_prot.h File Reference
include/fb_prot.h File Reference
Define the protocol specific definitions Implementation of the communication protocol.
#include "fb.h"
#include "msg_queue.h"
Data Structures
struct grp_addr_s
Structure for the group addresses.
struct fbus_hdr
Structure of the EIB header for each telegram.
Defines
#define PROT_EXT extern
Set PROT_EXT to extern to make clear it is include from an external source like a lib.
#define MSG_PRIO_SYSTEM 0
Mesage priority is system (highest priority, configuration and management)
#define MSG_PRIO_ALARM (1<<1)
Mesage priority is alarm (interface time 20-22ms)
#define MSG_PRIO_HIGH (1<<0)
Mesage priority is high (interface time > 22ms)
#define MSG_PRIO_LOW (1<<1 | 1<<0)
Mesage priority is low (interface time > 25ms)
#define MSG_MASK 0xC
Mask for the message priority.
#define T_BROADCAST_DATA 0x8000
A broadcast telegram.
#define T_BROADCAST_DATA_MASK 0x80FC
Mask for the broadcast telegram.
#define T_CONNECT_REQ 0x0080
A connect request.
#define T_CONNECT_REQ_MASK 0x80FF
Mask for the connect request.
#define T_DISCONNECT_REQ 0x0081
A disconnect request.
#define T_DISCONNECT_REQ_MASK 0x80FF
Mask for the disconnect request.
#define PROGRAMMING_MODE 0x81
value for programming mode
#define MONITOR_MODE 0x90
value for bus monitor mode
#define LINK_MODE 0x12
value for link layer mode
#define TRANSPORT_MODE 0x96
value for transport layer mode
#define APPLICATION_MODE 0x1E
value for application layer mode
#define RESET_MODE 0xC0
value for reset
#define BASE_ADDRESS_OFFSET 0x0100
Offset in BCU1 EEPROM.
#define MANUFACTORER_ADR_LOW 0x0104
Low address for manufactorer id.
#define MANUFACTORER_ADR 0x0104
Low address for manufactorer id.
#define DEVICE_NUMBER_HIGH 0x0105
High address for device id.
#define DEVICE_NUMBER_LOW 0x0106
Low address for device id.
#define SOFTWARE_VERSION_NUMBER 0x0107
Version number of the application.
#define APPLICATION_PROGRAMM 0x010C
Startadress of the application program.
#define PORT_A_DIRECTION_BIT 0x010C
Port A Direction Bit Setting.
#define APPLICATION_RUN_STATUS 0x010D
status of the application 0x00=run, 0xFF=stop
#define ROUTECOUNT 0x010E
#define ASSOCTABPTR 0x0111
start of associations in eeprom
#define COMMSTAB_ADDRESS 0x0112
COMMSTAB Pointer.
#define COUNT_GRP_ADDRESSES 0x0116
number of group addresses stored in EEPROM
#define PA_ADDRESS_HIGH 0x0117
high address for the physical address of the device
#define PA_ADDRESS_LOW 0x0118
low address for the physical address of the device
#define START_ADDRESS_GROUP_ADR 0x0119
address in eeprom where group addresses are stored
#define START_ADDRESS_GROUP_ADDRESSES 0x0119
address in eeprom where group addresses are stored */
Functions
PROT_EXT void sendExtTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
PROT_EXT void sendTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
PROT_EXT uint8_t findRespondGroupAddressByObjectNumber (uint8_t commObjectNumber, uint8_t offset)
Search through group address list and return the matching position of a group address which is an response address link.
PROT_EXT uint8_t fb_handlemsg (struct msg *rxmsg)
Queue message for handling.
PROT_EXT void fbprot_msg_handler (void)
That function is called from main loop.
PROT_EXT void fbprot_forward_msg (struct msg *rxmsg)
PROT_EXT void fbprot_Init (const STRUCT_DEFPARAM *pParam)
Read configuration from eeprom is existant or set default values and write them to the eeprom.
Variables
PROT_EXT uint16_t pa
the physical adress of the controller
Detailed Description
Define the protocol specific definitions Implementation of the communication protocol.
Author:
Dirk Opfer, Matthias Fechner, Christian Bode, Dirk Armbrust
Date:
Fri Dec 21 18:28:22 2007
Define Documentation
#define APPLICATION_MODE 0x1E
value for application layer mode
#define APPLICATION_PROGRAMM 0x010C
Startadress of the application program.
#define APPLICATION_RUN_STATUS 0x010D
status of the application 0x00=run, 0xFF=stop
Referenced by A_GroupValue_Read(), A_GroupValue_Write(), and timerOverflowFunction().
#define ASSOCTABPTR 0x0111
start of associations in eeprom
Referenced by find_ga(), findRespondGroupAddressByObjectNumber(), readApplication(), and runApplication().
#define BASE_ADDRESS_OFFSET 0x0100
Offset in BCU1 EEPROM.
#define COMMSTAB_ADDRESS 0x0112
COMMSTAB Pointer.
Referenced by processOutputs(), and read_obj_type().
#define COUNT_GRP_ADDRESSES 0x0116
number of group addresses stored in EEPROM
Referenced by read_grp_addr().
#define DEVICE_NUMBER_HIGH 0x0105
High address for device id.
Referenced by fbprot_Init().
#define DEVICE_NUMBER_LOW 0x0106
Low address for device id.
Referenced by fbprot_Init().
#define LINK_MODE 0x12
value for link layer mode
#define MANUFACTORER_ADR 0x0104
Low address for manufactorer id.
#define MANUFACTORER_ADR_LOW 0x0104
Low address for manufactorer id.
Todo:
delete define
#define MONITOR_MODE 0x90
value for bus monitor mode
#define MSG_MASK 0xC
Mask for the message priority.
#define MSG_PRIO_ALARM (1<<1)
Mesage priority is alarm (interface time 20-22ms)
#define MSG_PRIO_HIGH (1<<0)
Mesage priority is high (interface time > 22ms)
#define MSG_PRIO_LOW (1<<1 | 1<<0)
Mesage priority is low (interface time > 25ms)
#define MSG_PRIO_SYSTEM 0
Mesage priority is system (highest priority, configuration and management)
#define PA_ADDRESS_HIGH 0x0117
high address for the physical address of the device
Referenced by A_PhysicalAddress_Write(), fbprot_Init(), readApplication(), sendExtTelegram(), and sendTelegram().
#define PA_ADDRESS_LOW 0x0118
low address for the physical address of the device
Referenced by fbprot_Init(), readApplication(), sendExtTelegram(), and sendTelegram().
#define PORT_A_DIRECTION_BIT 0x010C
Port A Direction Bit Setting.
Todo:
delete define
#define PROGRAMMING_MODE 0x81
value for programming mode
#define PROT_EXT extern
Set PROT_EXT to extern to make clear it is include from an external source like a lib.
#define RESET_MODE 0xC0
value for reset
#define ROUTECOUNT 0x010E
Todo:
document variable
#define SOFTWARE_VERSION_NUMBER 0x0107
Version number of the application.
#define START_ADDRESS_GROUP_ADDRESSES 0x0119
address in eeprom where group addresses are stored */
Todo:
delete define
Referenced by read_grp_addr().
#define START_ADDRESS_GROUP_ADR 0x0119
address in eeprom where group addresses are stored
#define T_BROADCAST_DATA 0x8000
A broadcast telegram.
Referenced by check_addr().
#define T_BROADCAST_DATA_MASK 0x80FC
Mask for the broadcast telegram.
Referenced by check_addr().
#define T_CONNECT_REQ 0x0080
A connect request.
Referenced by check_addr().
#define T_CONNECT_REQ_MASK 0x80FF
Mask for the connect request.
Referenced by check_addr().
#define T_DISCONNECT_REQ 0x0081
A disconnect request.
Referenced by check_addr().
#define T_DISCONNECT_REQ_MASK 0x80FF
Mask for the disconnect request.
Referenced by check_addr().
#define TRANSPORT_MODE 0x96
value for transport layer mode
Function Documentation
PROT_EXT uint8_t fb_handlemsg (struct msg * rxmsg)
Queue message for handling.
That function will be called if a telegram was received completely.
Parameters:
rxmsg Pointer to message
Returns:
References queuemsg().
PROT_EXT void fbprot_Init (const STRUCT_DEFPARAM * pParam)
Read configuration from eeprom is existant or set default values and write them to the eeprom.
Configure and enable all interrupts.
<
Todo:
do not save group addresses in memory, read it from eeprom to save memory.
References DEBUG_NEWLINE, DEBUG_PUTS, DEVICE_NUMBER_HIGH, DEVICE_NUMBER_LOW, eeprom_ParamSetDefault(), eeprom_print(), mem_ReadByte(), pa, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, and read_grp_addr().
Referenced by main().
PROT_EXT void fbprot_msg_handler (void)
That function is called from main loop.
Todo:
disable this debugging, it crashes the controller if a telegram is received that is unkown
References fbus_hdr::apci, check_addr(), fb_cmd::cmd, COUNT_ARRAY_ELEMENTS, msg::data, DEBUG_NEWLINE, DEBUG_PUTC, DEBUG_PUTHEX, DEBUG_PUTS, dequeuemsg(), fbus_hdr::dest, FB_ACK, fb_hal_txqueue_msg(), fb_send_ack(), msg::flags, FreeMsg(), fb_cmd::func, msg::len, fb_cmd::mask, fb_cmd::max_len, fb_cmd::min_len, MSG_ALLOC, MSG_AUTOFREE, MSG_BRC, MSG_GRP, msg::next, fbus_hdr::npci, msg::state, fb_cmd::state, and fbus_hdr::tpci.
Referenced by main().
PROT_EXT uint8_t findRespondGroupAddressByObjectNumber (uint8_t commObjectNumber, uint8_t offset)
Search through group address list and return the matching position of a group address which is an response address link.
If no group address found return 0.
Parameters:
commObjectNumber The object of the group address (0-7)
offset Definition of offset for response addresses in EEPROM, 0x0C for 8-out
Returns:
Position in group address array grp_addr
References ASSOCTABPTR, BASE_ADDRESS_OFFSET, and mem_ReadByte().
Referenced by sendExtTelegram(), and sendTelegram().
PROT_EXT void sendExtTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
Only necessary if ports are switched inside a timer function.
Todo:
what source address to send if object has several group addresses?
Parameters:
commObjectNumber which port was switched
value 1=switched on, 0=switched of
offset Definition of offset for response addresses in EEPROM, 0x0C for 8-out
<
Todo:
that is application specific code maybe we should move it to another function
References AllocMsgI(), fbus_hdr::apci, fbus_hdr::ctrl, msg::data, fbus_hdr::dest, fb_hal_txqueue_msg(), findRespondGroupAddressByObjectNumber(), msg::flags, grp_addr_s::ga, grp_addr, msg::len, mem_ReadByte(), fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
PROT_EXT void sendTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
Only necessary if ports are switched inside a timer function.
Todo:
what source address to send if object has several group addresses?
Parameters:
commObjectNumber which port was switched
value 1=switched on, 0=switched of
offset Definition of offset for response addresses in EEPROM, 0x0C for 8-out
References AllocMsgI(), fbus_hdr::apci, fbus_hdr::ctrl, msg::data, fbus_hdr::dest, fb_hal_txqueue_msg(), findRespondGroupAddressByObjectNumber(), msg::flags, grp_addr_s::ga, grp_addr, msg::len, mem_ReadByte(), fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
Referenced by PortFunc_Jalousie(), PortFunc_Switch(), and processOutputs().
Variable Documentation
PROT_EXT uint16_t pa
the physical adress of the controller
Referenced by A_PhysicalAddress_Write(), check_addr(), fb_new_msg(), and fbprot_Init().