FreeBusAVR: app-8-out/fb_relais_app.c File Reference
app-8-out/fb_relais_app.c File Reference
The relais application to switch 8 relais Manufactorer code is 0x04 = Jung
Device type (2038.10) 0x2060 Ordernumber: 2138.10REG
.
#include "fb.h"
#include "fb_hardware.h"
#include "freebus-debug.h"
#include "fb_eeprom.h"
#include "msg_queue.h"
#include "fb_hal.h"
#include "fb_prot.h"
#include "fb_app.h"
#include "fb_relais_app.h"
Defines
#define RESET_RELOAD_APPLICATION_TIMER()
Reset the internal variables used for the application timer and reload the timer itself.
#define PWM_SETPOINT 0x64
configure pwm timer, we use timer2 for this 0xF2=4,8% duty cycle, 0xE6=10%, 0x01=100% The 74HCT573 is active low, changed to 0x33=51 -> This is about 20% negative duty cycle
#define PWM_DELAY_TIME 10
How long we hold the relais at 100% before we enable PWM again.
Functions
void timerOverflowFunction (void)
Timer1 is used as application timer.
void switchObjects (void)
Switch the objects to state in portValue and save value to eeprom if necessary.
void switchPorts (uint8_t port)
switch all of the output pins
ISR (TIMER1_COMPB_vect)
ISR is called if on TIMER1 the comparator B matches the defined condition.
uint8_t restartApplication (void)
Function is called when microcontroller gets power or if the application must be restarted.
uint8_t readApplication (struct msg *rxmsg)
Read status from port and return it.
uint8_t runApplication (struct msg *rxmsg)
Function is called if A_GroupValue_Write is received.
int main (void)
The start point of the program, init all libraries, start the bus interface, the application and check the status of the program button.
Variables
struct grp_addr_s grp_addr
List of saved group addresses for this controller, see struct grp_addr_s for more information.
static uint8_t portValue
defines the port status.
static uint16_t currentTime
defines the current time in 10ms steps (2=20ms)
static uint8_t currentTimeOverflow
the amount of overflows from currentTime
static uint8_t currentTimeOverflowBuffer
is set to one if overflow happened, is 0 if overflow was processed
static uint16_t delayValues [8]
save value for delays
static uint8_t timerRunning
bit is set if timer is running
static uint8_t waitToPWM
defines wait time until PWM get active again (counts down in 130ms steps), 1==enable PWM, 0==no change
uint8_t nodeParam [EEPROM_SIZE]
parameterstructure (RAM)
const STRUCT_DEFPARAM
defaultParam[] PROGMEM
list of the default parameter for this application
Detailed Description
The relais application to switch 8 relais Manufactorer code is 0x04 = Jung
Device type (2038.10) 0x2060 Ordernumber: 2138.10REG
.
Author:
Matthias Fechner, Christian Bode
Date:
Sat Jan 05 17:44:47 2008
To enable IO test compile with -DIO_TEST
Define Documentation
#define PWM_DELAY_TIME 10
How long we hold the relais at 100% before we enable PWM again.
Referenced by switchObjects().
#define PWM_SETPOINT 0x64
configure pwm timer, we use timer2 for this 0xF2=4,8% duty cycle, 0xE6=10%, 0x01=100% The 74HCT573 is active low, changed to 0x33=51 -> This is about 20% negative duty cycle
Referenced by restartApplication(), and timerOverflowFunction().
#define RESET_RELOAD_APPLICATION_TIMER ()
Value:
{      \
        currentTimeOverflow=0;                  \
        currentTimeOverflowBuffer=0;            \
        currentTime=0;                          \
        RELOAD_APPLICATION_TIMER();             \
    }
Reset the internal variables used for the application timer and reload the timer itself.
Todo:
check if move of currentTime to this function really does not introduce a bug
Function Documentation
ISR (TIMER1_COMPB_vect)
ISR is called if on TIMER1 the comparator B matches the defined condition.
int main (void)
The start point of the program, init all libraries, start the bus interface, the application and check the status of the program button.
Returns:
Todo:
Funktion fuer CRC-Check bei PowerOn fehlt noch
References CLEAR_TIMER1_OVERRUN, DEBUG_INIT, DEBUG_NEWLINE, DEBUG_PUTS, DISABLE_WATCHDOG, eeprom_Init(), EEPROM_SIZE, ENABLE_ALL_INTERRUPTS, fbhal_checkProgTaster(), fbhal_Init(), fbprot_Init(), msg_queue_init(), nodeParam, restartApplication(), sendTestTelegram(), TIMER1_OVERRUN, and timerOverflowFunction().
uint8_t readApplication (struct msg * rxmsg)
Read status from port and return it.
Parameters:
rxmsg
Returns:
Todo:
check if read value is allowed
Todo:
declaration hides hdr line 268
Todo:
write part additional functions
References AllocMsgI(), fbus_hdr::apci, ASSOCTABPTR, BASE_ADDRESS_OFFSET, fbus_hdr::ctrl, msg::data, DEBUG_PUTS, fbus_hdr::dest, eeprom_ParamRead(), FB_ACK, fb_hal_txqueue_msg(), FB_NACK, grp_addr_s::ga, grp_addr, K1dimmwert_ausgang, K2dimmwert_ausgang, msg::len, fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, portValue, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
uint8_t restartApplication (void)
Function is called when microcontroller gets power or if the application must be restarted.
It restores data like in the parameters defined.
Returns:
FB_ACK or FB_NACK
References anspringen_k1, anspringen_k2, currentTime, currentTimeOverflow, eeprom_ParamRead(), einschathellikeit_k1, einschathellikeit_k2, ENABLE_PWM, hellikeit, IO_OUTPUT, K1dimmwert, MAXDIMMWERT, mindimmwert_k1, mindimmwert_k2, portValue, PWM_SETPOINT, RELOAD_APPLICATION_TIMER, switchObjects(), timerRunning, and waitToPWM.
uint8_t runApplication (struct msg * rxmsg)
Function is called if A_GroupValue_Write is received.
Function is called if A_GroupValue_Write is received it is the function "EIS1" or "Data Type Boolean" for the relais module.
The type it is the function "EIS1" or "Data Type Boolean" for the relais module. Read all parameters in that function and set global variables.
Parameters:
rxmsg
Returns:
The return value defies if a ACK or a NACK should be sent (FB_ACK, FB_NACK)
Todo:
handle data with more then 6 bit
Todo:
check if object is blocked and/or write is enabled
Todo:
check how to handle switch off if timer is currently active (0x01EB)
check for delays
Todo:
write part additional functions
References fbus_hdr::apci, ASSOCTABPTR, BASE_ADDRESS_OFFSET, COMMSTAB_ADDRESS, currentTime, msg::data, DEBUG_NEWLINE, DEBUG_PUTC, DEBUG_PUTHEX, DEBUG_PUTS, DEBUG_SPACE, delayValues, fbus_hdr::dest, eeprom_ParamRead(), einschathellikeit_k1, einschathellikeit_k2, FB_ACK, grp_addr_s::ga, gK1helldunkel, gK2helldunkel, grp_addr, hellikeit, K1dimmwert, K2dimmwert, msg::len, portValue, RESET_RELOAD_APPLICATION_TIMER, switchObjects(), and timerRunning.
void switchObjects (void)
Switch the objects to state in portValue and save value to eeprom if necessary.
< defines if IO is closer or opener, see address 0x01F2 in eeprom
References DEBUG_NEWLINE, DEBUG_PUTS, eeprom_ParamRead(), eeprom_ParamWrite(), ENABLE_PWM, portValue, PWM_DELAY_TIME, switchPorts(), and waitToPWM.
Referenced by restartApplication(), runApplication(), and timerOverflowFunction().
void switchPorts (uint8_t port)
switch all of the output pins
Parameters:
port
Referenced by switchObjects().
void timerOverflowFunction (void)
Timer1 is used as application timer.
It increase the variable currentTime every 130ms and currentTimeOverflow if currentTime runs over 16-bit.
Returns:
Todo:
test interrupt lock in this function that it is not disturbing TX and RX of telegrams
Todo:
Problem bei einem Timerueberlauf !!!
References APPLICATION_RUN_STATUS, currentTime, currentTimeOverflow, DEBUG_NEWLINE, DEBUG_PUTHEX, DEBUG_PUTS, delayValues, DISABLE_IRQS, eeprom_ParamRead(), ENABLE_IRQS, ENABLE_PWM, portValue, PWM_SETPOINT, sendTelegram(), switchObjects(), timerRunning, and waitToPWM.
Variable Documentation
uint16_t currentTime [static]
defines the current time in 10ms steps (2=20ms)
uint8_t currentTimeOverflow [static]
the amount of overflows from currentTime
Referenced by restartApplication(), and timerOverflowFunction().
uint8_t currentTimeOverflowBuffer [static]
is set to one if overflow happened, is 0 if overflow was processed
uint16_t delayValues[8] [static]
save value for delays
Referenced by runApplication(), and timerOverflowFunction().
struct grp_addr_s grp_addr
List of saved group addresses for this controller, see struct grp_addr_s for more information.
uint8_t nodeParam[EEPROM_SIZE]
parameterstructure (RAM)
uint8_t portValue [static]
defines the port status.
LSB IO0 and MSB IO8, ports with delay can be set to 1 here but will be switched delayed depending on the delay
Referenced by readApplication(), restartApplication(), runApplication(), switchObjects(), and timerOverflowFunction().
const STRUCT_DEFPARAM defaultParam [] PROGMEM
Initial value:
    {
        { MANUFACTORER_ADR,        0x04 },
        { DEVICE_NUMBER_HIGH,      0x20 },
        { DEVICE_NUMBER_LOW,       0x60 },
        { SOFTWARE_VERSION_NUMBER, 0x01 },
        { APPLICATION_RUN_STATUS,  0xFF },
        { COMMSTAB_ADDRESS,        0x9A },
        { APPLICATION_PROGRAMM,    0x00 },
        { 0x0000,                  0x00 },
        { 0x01EA,                  0x00 },
        { 0x01F6,                  0x55 },
        { 0x01F7,                  0x55 },
        { 0x01F2,                  0x00 },
        { PA_ADDRESS_HIGH,         0x11 },
        { PA_ADDRESS_LOW,          0x33 },
        { 0xFF,                    0xFF }
    }
list of the default parameter for this application
uint8_t timerRunning [static]
bit is set if timer is running
Referenced by restartApplication(), runApplication(), and timerOverflowFunction().
uint8_t waitToPWM [static]
defines wait time until PWM get active again (counts down in 130ms steps), 1==enable PWM, 0==no change
Referenced by restartApplication(), switchObjects(), and timerOverflowFunction().