FreeBusAVR: lib/fb_prot.c File Reference
lib/fb_prot.c File Reference
Handle all requests which are EIB bases like write current address or group address.
#include "fb.h"
#include "fb_hardware.h"
#include "freebus-debug.h"
#include "fb_eeprom.h"
#include "fb_app.h"
#include "fb_hal.h"
#include "rf22.h"
#include "fbrf_prot.h"
#include "fb_prot.h"
Data Structures
struct fb_cmd
structure which saves all EIB commands
struct ucd_stat
Track status of connections if connection is opened with T_Connect_Req.
Defines
#define _FB_PROT_C
#define MSG_MUL (1<<1)
Multicast address, one-to-many, connection-less.
#define MSG_BRC (1<<7)
Broadcast adress, one-to-all conenction-less.
#define MSG_DAF (1<<1)
Direct adressing, one-to-one.
#define MSG_GRP (1<<6)
Group adress.
#define MSG_CON (1<<5)
connect request
#define MSG_DIS (1<<4)
disconnect request
#define FW_MASK nodeParam[NODEPARAM_SIZE - 6]
#define FW_PA nodeParam[NODEPARAM_SIZE - 7]
Functions
static void read_grp_addr (void)
Read the group addresses from the eeprom and save them in the struct grp_addr.
static struct msg * fb_new_msg (uint8_t *dest, uint8_t payload_len)
Create a new telegram and and return pointer to it.
static uint8_t A_PhysicalAddress_Write (struct msg *rxmsg)
Set the received address as our new device address.
static uint8_t A_PhysicalAddress_Read (struct msg *rxmsg)
Returns the address of the device.
static uint8_t T_Connect_Req (struct msg *rxmsg)
Called to start a connection to a physical address.
static uint8_t T_Disconnect_Req (struct msg *rxmsg)
Release the transport connection.
static void ncd_resp (struct msg *rxmsg)
Sicherungslayer.
static uint8_t A_DeviceDescriptor_Read (struct msg *rxmsg)
Is called if information for the BCU type is requested.
static uint8_t A_Memory_Read (struct msg *rxmsg)
Read data from eeprom and return send it as telegram back to the requester.
static uint8_t A_Memory_Write (struct msg *rxmsg)
Write recieved data to the eeprom.
static uint8_t A_ADC_Read (struct msg *rxmsg)
Read the values from the ADC converter.
static uint8_t A_Restart (struct msg *rxmsg)
Restart the program on the microcontroller.
static uint8_t Ignore (struct msg *rxmsg)
Send aknowledge to certain message.
static uint8_t A_GroupValue_Read (struct msg *rxmsg)
A read request to the application.
static uint8_t A_GroupValue_Write (struct msg *rxmsg)
Is called if a broadcast is received with a matching group address (eg.
static uint8_t check_addr (struct fbus_hdr *hdr)
Analyse the type of the message (broadcast, direct, group address) and check for physical and group address if the telegram is for us.
void sendExtTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
void sendTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
uint8_t findRespondGroupAddressByObjectNumber (uint8_t commObjectNumber, uint8_t offset)
Search through group address list and return the matching position of a group address which is an response address link.
uint8_t fb_handlemsg (struct msg *rxmsg)
Queue message for handling.
void fbprot_msg_handler (void)
That function is called from main loop.
void fbprot_Init (const STRUCT_DEFPARAM *pParam)
Read configuration from eeprom is existant or set default values and write them to the eeprom.
Variables
uint8_t nodeParam []
parameterstructure (RAM)
struct grp_addr_s grp_addr
List of saved group addresses for this controller, see struct grp_addr_s for more information.
static struct ucd_stat ucd
Used to track transport connections, for this source address, status and counter is saved.
static struct msg * rx_ptr
struct fb_cmd bus_cmds[] PROGMEM
Store mapping of function with parameters called by bus memebers.
Detailed Description
Handle all requests which are EIB bases like write current address or group address.
Author:
Dirk Opfer, Matthias Fechner, Christian Bode, Dirk Armbrust
Date:
Fri Oct 26 18:14:05 2007
Description of a telegram:
A telegram consists of the following bytes:
8-bit: controll byte
16-bit: source address
16-bit: destination address
3-bit: routing counter
4-bit: length of user data
2-16 byte: user data
8-bit: CRC byte
Each byte is build up in the following way: S01234567PS
S=Start bit (always 1)
0=data bit (LSB)
1-6=data
7=data (MSB)
P=parity bit
S=stop bit (always 1)
Todo:
Hier sollten die Bezeichnungen (apdu, ...) noch mal überarbeitet werden. Ziel sollte es sein diese aus der Spec zu entnehmen.
Reduce debugging again.
Handle group address zero which is a broadcast to all devices.
Define Documentation
#define MSG_BRC (1<<7)
Broadcast adress, one-to-all conenction-less.
Referenced by check_addr(), and fbprot_msg_handler().
#define MSG_CON (1<<5)
connect request
Referenced by check_addr().
#define MSG_DAF (1<<1)
Direct adressing, one-to-one.
Referenced by check_addr().
#define MSG_DIS (1<<4)
disconnect request
Referenced by check_addr().
#define MSG_GRP (1<<6)
Group adress.
Referenced by check_addr(), and fbprot_msg_handler().
#define MSG_MUL (1<<1)
Multicast address, one-to-many, connection-less.
Function Documentation
static uint8_t A_ADC_Read (struct msg * rxmsg) [static]
Read the values from the ADC converter.
We don't have that so it is only a dummy to speed up programming and reading of the devices.
Parameters:
rxmsg
Returns:
References fbus_hdr::apci, ucd_stat::count, msg::data, FB_ACK, fb_hal_txqueue_msg(), fb_new_msg(), FB_NONE, fb_send_ack(), ncd_resp(), fbus_hdr::npci, fbus_hdr::src, fbus_hdr::tpci, and ucd.
static uint8_t A_DeviceDescriptor_Read (struct msg * rxmsg) [static]
Is called if information for the BCU type is requested.
Function triggers a send which return information about the BCU.
Parameters:
rxmsg Pointer to received telegram
Returns:
FB_ACK: everything is fine, FB_NONE: Response telegram could not be created
References fbus_hdr::apci, msg::data, FB_ACK, fb_hal_txqueue_msg(), fb_new_msg(), FB_NONE, fb_send_ack(), ncd_resp(), fbus_hdr::npci, fbus_hdr::src, and fbus_hdr::tpci.
static uint8_t A_GroupValue_Read (struct msg * rxmsg) [static]
A read request to the application.
Parameters:
rxmsg
Returns:
References APPLICATION_RUN_STATUS, DEBUG_NEWLINE, DEBUG_PUTS, FB_ACK, FB_NACK, fb_send_ack(), mem_ReadByte(), and readApplication().
static uint8_t A_GroupValue_Write (struct msg * rxmsg) [static]
Is called if a broadcast is received with a matching group address (eg.
button is pressed to switch relais on or off).
Parameters:
rxmsg
Todo:
handle message shorter then 6-bit
Returns:
References APPLICATION_RUN_STATUS, FB_ACK, FB_NACK, fb_send_ack(), mem_ReadByte(), and runApplication().
static uint8_t A_Memory_Read (struct msg * rxmsg) [static]
Read data from eeprom and return send it as telegram back to the requester.
Parameters:
rxmsg
Returns:
References fbus_hdr::apci, ucd_stat::count, msg::data, FB_ACK, fb_hal_txqueue_msg(), fb_new_msg(), FB_NONE, fb_send_ack(), msg::len, mem_ReadByte(), ncd_resp(), fbus_hdr::npci, fbus_hdr::src, fbus_hdr::tpci, and ucd.
static uint8_t A_Memory_Write (struct msg * rxmsg) [static]
Write recieved data to the eeprom.
Parameters:
rxmsg
Returns:
References fbus_hdr::apci, msg::data, FB_ACK, fb_send_ack(), mem_WriteBlock(), and ncd_resp().
static uint8_t A_PhysicalAddress_Read (struct msg * rxmsg) [static]
Returns the address of the device.
The device must be in programming mode for this. Only one device can be in programming mode. See 3.2.2 in EIB specification
Parameters:
rxmsg
Returns:
References fbus_hdr::apci, fbus_hdr::ctrl, msg::data, FB_ACK, fb_hal_txqueue_msg(), fb_new_msg(), fb_send_ack(), SS_PROG, systemState, and fbus_hdr::tpci.
static uint8_t A_PhysicalAddress_Write (struct msg * rxmsg) [static]
Set the received address as our new device address.
For this function the device must be in programming mode. Only one device can be in programming mode. See 3.2.1 in EIB specification.
Parameters:
rxmsg
Returns:
References BASE_ADDRESS_OFFSET, msg::data, FB_ACK, FB_NONE, fb_send_ack(), mem_WriteBlock(), NODEPARAM_SIZE, pa, PA_ADDRESS_HIGH, SS_PROG, and systemState.
static uint8_t A_Restart (struct msg * rxmsg) [static]
Restart the program on the microcontroller.
Parameters:
rxmsg
Returns:
References DEBUG_PUTC, eeprom_busy(), and fb_hal_restart().
static uint8_t check_addr (struct fbus_hdr * hdr) [inline, static]
Analyse the type of the message (broadcast, direct, group address) and check for physical and group address if the telegram is for us.
Todo:
must we handle group address 0/0/0 here in a special way?
Parameters:
hdr
Returns:
References grp_addr_s::count, fbus_hdr::dest, grp_addr_s::ga, grp_addr, MSG_BRC, MSG_CON, MSG_DAF, MSG_DIS, MSG_GRP, fbus_hdr::npci, pa, T_BROADCAST_DATA, T_BROADCAST_DATA_MASK, T_CONNECT_REQ, T_CONNECT_REQ_MASK, T_DISCONNECT_REQ, T_DISCONNECT_REQ_MASK, and fbus_hdr::tpci.
Referenced by fbprot_msg_handler().
uint8_t fb_handlemsg (struct msg * rxmsg)
Queue message for handling.
That function will be called if a telegram was received completely.
Parameters:
rxmsg Pointer to message
Returns:
References queuemsg().
static struct msg * fb_new_msg (uint8_t * dest, uint8_t payload_len) [static, read]
Create a new telegram and and return pointer to it.
Parameters:
dest Pointer to the destination address
payload_len
Returns:
References AllocMsgI(), fbus_hdr::ctrl, msg::data, fbus_hdr::dest, msg::len, fbus_hdr::npci, pa, msg::repeat, and fbus_hdr::src.
Referenced by A_ADC_Read(), A_DeviceDescriptor_Read(), A_Memory_Read(), A_PhysicalAddress_Read(), and ncd_resp().
void fbprot_Init (const STRUCT_DEFPARAM * pParam)
Read configuration from eeprom is existant or set default values and write them to the eeprom.
Configure and enable all interrupts.
<
Todo:
do not save group addresses in memory, read it from eeprom to save memory.
References DEBUG_NEWLINE, DEBUG_PUTS, DEVICE_NUMBER_HIGH, DEVICE_NUMBER_LOW, eeprom_ParamSetDefault(), eeprom_print(), mem_ReadByte(), pa, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, and read_grp_addr().
Referenced by main().
void fbprot_msg_handler (void)
That function is called from main loop.
Todo:
disable this debugging, it crashes the controller if a telegram is received that is unkown
References fbus_hdr::apci, check_addr(), fb_cmd::cmd, COUNT_ARRAY_ELEMENTS, msg::data, DEBUG_NEWLINE, DEBUG_PUTC, DEBUG_PUTHEX, DEBUG_PUTS, dequeuemsg(), fbus_hdr::dest, FB_ACK, fb_hal_txqueue_msg(), fb_send_ack(), msg::flags, FreeMsg(), fb_cmd::func, msg::len, fb_cmd::mask, fb_cmd::max_len, fb_cmd::min_len, MSG_ALLOC, MSG_AUTOFREE, MSG_BRC, MSG_GRP, msg::next, fbus_hdr::npci, msg::state, fb_cmd::state, and fbus_hdr::tpci.
Referenced by main().
uint8_t findRespondGroupAddressByObjectNumber (uint8_t commObjectNumber, uint8_t offset)
Search through group address list and return the matching position of a group address which is an response address link.
If no group address found return 0.
Parameters:
commObjectNumber The object of the group address (0-7)
offset Definition of offset for response addresses in EEPROM, 0x0C for 8-out
Returns:
Position in group address array grp_addr
References ASSOCTABPTR, BASE_ADDRESS_OFFSET, and mem_ReadByte().
Referenced by sendExtTelegram(), and sendTelegram().
static uint8_t Ignore (struct msg * rxmsg) [static]
Send aknowledge to certain message.
Todo:
Not implemented yet
Parameters:
rxmsg The received telegram
Returns:
0
References FB_ACK, and fb_send_ack().
static void ncd_resp (struct msg * rxmsg) [static]
Sicherungslayer.
Parameters:
rxmsg pointer to currently received eib telegram
References msg::data, fb_hal_txqueue_msg(), fb_new_msg(), fbus_hdr::npci, fbus_hdr::src, and fbus_hdr::tpci.
Referenced by A_ADC_Read(), A_DeviceDescriptor_Read(), A_Memory_Read(), and A_Memory_Write().
static void read_grp_addr (void) [static]
Read the group addresses from the eeprom and save them in the struct grp_addr.
References grp_addr_s::count, COUNT_GRP_ADDRESSES, DEBUG_PUTHEX, DEBUG_PUTS, DEBUG_SPACE, FB_MAX_GROUP_ADDR, grp_addr_s::ga, grp_addr, mem_ReadByte(), and START_ADDRESS_GROUP_ADDRESSES.
Referenced by fbprot_Init().
void sendExtTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
Only necessary if ports are switched inside a timer function.
Todo:
what source address to send if object has several group addresses?
Parameters:
commObjectNumber which port was switched
value 1=switched on, 0=switched of
offset Definition of offset for response addresses in EEPROM, 0x0C for 8-out
<
Todo:
that is application specific code maybe we should move it to another function
References AllocMsgI(), fbus_hdr::apci, fbus_hdr::ctrl, msg::data, fbus_hdr::dest, fb_hal_txqueue_msg(), findRespondGroupAddressByObjectNumber(), msg::flags, grp_addr_s::ga, grp_addr, msg::len, mem_ReadByte(), fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
void sendTelegram (uint8_t commObjectNumber, uint8_t value, uint8_t offset)
Send telegram as response to signal current state of the port to other devices.
Only necessary if ports are switched inside a timer function.
Todo:
what source address to send if object has several group addresses?
Parameters:
commObjectNumber which port was switched
value 1=switched on, 0=switched of
offset Definition of offset for response addresses in EEPROM, 0x0C for 8-out
References AllocMsgI(), fbus_hdr::apci, fbus_hdr::ctrl, msg::data, fbus_hdr::dest, fb_hal_txqueue_msg(), findRespondGroupAddressByObjectNumber(), msg::flags, grp_addr_s::ga, grp_addr, msg::len, mem_ReadByte(), fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
Referenced by PortFunc_Jalousie(), PortFunc_Switch(), and processOutputs().
static uint8_t T_Connect_Req (struct msg * rxmsg) [static]
Called to start a connection to a physical address.
Only accepted if no conenction is established yet. Only acknowledge byte is returned no confirmation telegram is sent.
Parameters:
rxmsg
Returns:
References ucd_stat::addr, ucd_stat::count, msg::data, FB_ACK, FB_NONE, fb_send_ack(), fbus_hdr::src, ucd_stat::status, and ucd.
static uint8_t T_Disconnect_Req (struct msg * rxmsg) [static]
Release the transport connection.
Parameters:
rxmsg
Returns:
References ucd_stat::addr, ucd_stat::count, msg::data, FB_ACK, FB_NONE, fb_send_ack(), fbus_hdr::src, ucd_stat::status, and ucd.
Variable Documentation
struct grp_addr_s grp_addr
List of saved group addresses for this controller, see struct grp_addr_s for more information.
Referenced by check_addr(), find_ga(), read_grp_addr(), readApplication(), runApplication(), sendExtTelegram(), and sendTelegram().
uint8_t nodeParam[]
parameterstructure (RAM)
Referenced by eeprom_Init(), and main().
struct fb_cmd bus_cmds [] PROGMEM
Initial value:
 {
    {              MSG_GRP , 0x0080, 0x03C0, 0x00, 0x0E, A_GroupValue_Write },
    {              MSG_GRP , 0x0000, 0x03FF, 0x00, 0x10, A_GroupValue_Read },
    {              MSG_CON , 0x0000, 0x0000, 0x01, 0x01, T_Connect_Req },
    {              MSG_DIS , 0x0000, 0x0000, 0x01, 0x01, T_Disconnect_Req },
    {              MSG_DAF , 0xC200, 0xC300, 0x01, 0x01, Ignore},
    {    MSG_BRC | MSG_DAF , 0x00C0, 0x03FF, 0x04, 0x04, A_PhysicalAddress_Write },
    {    MSG_BRC | MSG_DAF , 0x0100, 0x03FF, 0x02, 0x02, A_PhysicalAddress_Read },
    {              MSG_DAF , 0x0180, 0x03C0, 0x03, 0x03, A_ADC_Read },
    {              MSG_DAF , 0x4200, 0xC3C0, 0x04, 0x04, A_Memory_Read },
    {              MSG_DAF , 0x4280, 0xC3C0, 0x01, 0x10, A_Memory_Write },
    {              MSG_DAF , 0x4300, 0xFFFF, 0x02, 0x02, A_DeviceDescriptor_Read },
    {              MSG_DAF , 0x0380, 0x03FF, 0x02, 0x02, A_Restart},
}
Store mapping of function with parameters called by bus memebers.
struct ucd_stat ucd [static]
Used to track transport connections, for this source address, status and counter is saved.
Referenced by A_ADC_Read(), A_Memory_Read(), T_Connect_Req(), and T_Disconnect_Req().