FreeBusAVR: include/fb_hal.h File Reference
include/fb_hal.h File Reference
Definitions on Hardware Abstration Layer.
#include <avr/io.h>
#include <avr/interrupt.h>
#include "msg_queue.h"
Defines
#define HAL_EXT extern
Set HAL_EXT to extern to make clear it is include from an external source like a lib.
#define FB_FRAME_ERR (1 << 7)
Error error, e.g. stop bit is missing.
#define FB_PARITY_ERR (1 << 6)
Parity error in octet.
#define FB_COLLISION (1 << 5)
Collision detected.
#define FB_CHAR_REC (1 << 3)
In character receive mode.
#define FB_BUS_FREE (1 << 2)
EIB bus is free and messages can be send.
#define FB_ACK_REC (1 << 1)
In acknowledge receive mode.
#define FB_MESSAGE (1 << 0)
Message type is a EIB message.
#define OFF 0U
Global Define: OFF = 0.
#define ON 1U
Global Define: ON = 1.
#define IO_INPUT 0U
Portpin-Direction is Input.
#define IO_OUTPUT 1U
Portpin-Direction is Output.
#define PANIC_MEMORY 0x01
Memory error, is set when no memory is left and it is tried to allocate memory.
#define PANIC_RESOURCE 0x02
No more resources are available.
#define PANIC_EEPROM 0x03
Error in eeprom.
#define PANIC_NO_MSG 0x04
No more space for messages is left in allocated message queue.
#define _NOP() do { __asm__ __volatile__ ("nop"); } while (0)
define _NOP which calls assembler routine nop.
Functions
HAL_EXT uint8_t fbhal_checkProgTaster (void)
Check the programm button and set programming mode and switch LED depending on programming mode.
HAL_EXT void fbhal_Init (void)
Set input/output mode to PORTs, init timers and interrupts.
HAL_EXT void fb_send_ack (uint8_t value)
Function to set the ack value for the response to a telegram which must be send in a absolutly excat timing.
HAL_EXT void fb_hal_restart (void)
Restart the application by activating the watchdog and block the program.
HAL_EXT uint8_t fb_hal_txqueue_msg (struct msg *tx)
Queue message for sending.
HAL_EXT void sendTestTelegram (void)
That function can be use to send a test telegramm to the bus, e.g.
HAL_EXT void panic (uint8_t reason)
Hold application and set blink code to PORTB pin 0, our prog pin and LED.
Variables
HAL_EXT uint8_t systemState
Holds the system state.
Detailed Description
Definitions on Hardware Abstration Layer.
Author:
Dirk Opfer, Matthias Fechner, Christian Bode
Date:
Tue Jan 08 11:19:00 2008
Define Documentation
#define _NOP () do { __asm__ __volatile__ ("nop"); } while (0)
define _NOP which calls assembler routine nop.
Can be used to wait some time and/or to prevent compiler from removing code in optimization (empty loops to wait etc.)
Referenced by main().
#define FB_ACK_REC (1 << 1)
In acknowledge receive mode.
#define FB_BUS_FREE (1 << 2)
EIB bus is free and messages can be send.
Referenced by fbhal_Init(), ISR(), retrigger_tx(), sendTestTelegram(), and timer_bus_free().
#define FB_CHAR_REC (1 << 3)
In character receive mode.
#define FB_COLLISION (1 << 5)
Collision detected.
Referenced by checkForCollisions(), and tx_error().
#define FB_FRAME_ERR (1 << 7)
Error error, e.g. stop bit is missing.
Referenced by timer_rec_chars(), and timer_timeout().
#define FB_MESSAGE (1 << 0)
Message type is a EIB message.
Referenced by timer_timeout().
#define FB_PARITY_ERR (1 << 6)
Parity error in octet.
Referenced by timer_rec_chars(), and timer_timeout().
#define HAL_EXT extern
Set HAL_EXT to extern to make clear it is include from an external source like a lib.
#define IO_INPUT 0U
Portpin-Direction is Input.
Referenced by fbhal_Init(), and restartApplication().
#define IO_OUTPUT 1U
Portpin-Direction is Output.
Referenced by fbhal_Init(), panic(), and restartApplication().
#define OFF 0U
Global Define: OFF = 0.
Referenced by checkForCollisions(), fbhal_Init(), and panic().
#define ON 1U
Global Define: ON = 1.
Referenced by ISR(), and panic().
#define PANIC_EEPROM 0x03
Error in eeprom.
#define PANIC_MEMORY 0x01
Memory error, is set when no memory is left and it is tried to allocate memory.
#define PANIC_NO_MSG 0x04
No more space for messages is left in allocated message queue.
Referenced by AllocMsgI().
#define PANIC_RESOURCE 0x02
No more resources are available.
Function Documentation
HAL_EXT void fb_hal_restart (void) [inline]
Restart the application by activating the watchdog and block the program.
References ENABLE_WATCHDOG.
Referenced by A_Restart().
HAL_EXT uint8_t fb_hal_txqueue_msg (struct msg * tx)
Queue message for sending.
Parameters:
tx Pointer to message
Returns:
References queuemsg(), and retrigger_tx().
Referenced by A_ADC_Read(), A_DeviceDescriptor_Read(), A_Memory_Read(), A_PhysicalAddress_Read(), ncd_resp(), readApplication(), sendExtTelegram(), sendTelegram(), and sendTestTelegram().
HAL_EXT void fb_send_ack (uint8_t value) [inline]
Function to set the ack value for the response to a telegram which must be send in a absolutly excat timing.
Parameters:
value Ackvalue can be FB_ACK, FB_NACK, FB_BUSY and FB_NONE
References DEBUG_PUTS, FB_ACK, and fb_ackvalue.
Referenced by A_ADC_Read(), A_DeviceDescriptor_Read(), A_GroupValue_Read(), A_GroupValue_Write(), A_Memory_Read(), A_Memory_Write(), A_PhysicalAddress_Read(), A_PhysicalAddress_Write(), Ignore(), T_Connect_Req(), T_Disconnect_Req(), and timer_timeout().
HAL_EXT uint8_t fbhal_checkProgTaster (void)
Check the programm button and set programming mode and switch LED depending on programming mode.
Programm button is on PB0 and pin 4 on Freebus connector.
Function detects the state of the prog button (debounced) and sets the programming mode. This is done only every 16th call, because the µC needs some time to switch from output to input mode and so we got more negative duty cylce for the prog led.
Bug:
The macro SET_IO_PROG(IO_OUTPUT) could not be used here, because this sets the DDR and also the PORT = 0. This won't work.
Todo:
Check if this function is working fine.
Author:
Matthias Fechner, Tobias Buss
References DEBUG_PUTS, delay, PROG_DDR, PROG_PIN, PROG_PORT, SS_PROG, and systemState.
Referenced by main().
HAL_EXT void fbhal_Init (void)
Set input/output mode to PORTs, init timers and interrupts.
Todo:
Timer und Interrupt-Register konfigurieren
Todo:
define a macro for following instructions in freebus-atmegaxxx.h
References CONFIGURE_INT0, EIB_BIT_TIME, EIB_NONE_MODE, EIB_TX_LOWTIME, FB_BUS_FREE, fb_frame, fbstat, IO_INPUT, IO_OUTPUT, next_rx_state(), OFF, operationMode, rxframe, systemState, and TS_WAITING_CHARS.
Referenced by main().
HAL_EXT void panic (uint8_t reason)
Hold application and set blink code to PORTB pin 0, our prog pin and LED.
Todo:
Replace that function with a mechanism that not completely kills the controller application
Parameters:
reason
Todo:
Replace that function with a mechanism that not completely kills the controller application
Parameters:
reason
Referenced by AllocMsgI().
HAL_EXT void sendTestTelegram (void)
That function can be use to send a test telegramm to the bus, e.g.
to measure signal levels in circuit.
References AllocMsgI(), fbus_hdr::apci, fbus_hdr::ctrl, msg::data, DEBUG_NEWLINE, DEBUG_PUTS, fbus_hdr::dest, eeprom_ParamRead(), FB_BUS_FREE, fb_hal_txqueue_msg(), fbstat, msg::len, fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
Referenced by main().
Variable Documentation
HAL_EXT uint8_t systemState
Holds the system state.
Todo:
give more detailed explaination
Referenced by A_PhysicalAddress_Read(), A_PhysicalAddress_Write(), eeprom_ParamRead(), eeprom_ParamWrite(), fbhal_checkProgTaster(), and fbhal_Init().