FreeBusAVR: lib/fb_hal.c File Reference
lib/fb_hal.c File Reference
Freebus Hardware Layer. Implementation of a software- uart + timer handling This file consists of function which are bound to the hardware For further information check the pdf 03_02_02 Communication Medium TP 1 v1.0 AS.PDF.
#include "fb.h"
#include "fb_hardware.h"
#include "freebus-debug.h"
#include "fb_eeprom.h"
#include "fb_prot.h"
#include "fb_hal.h"
Defines
#define EIB_BIT_TIME 104U
duration of one bit on the EIB
#define EIB_TX_LOWTIME 40U
How long we hold the level on that value (35us).
#define EIB_TX_HIGHTIME EIB_BIT_TIME-EIB_TX_LOWTIME
for the rest of the time the bus is high
#define EIB_NONE_MODE 0
the receive and sending part is in idle mode
#define EIB_SEND_MODE (1<<0)
defines that we're in send mode, if the ISR is triggered the send functions are called
#define EIB_RECEIVE_MODE (1<<1)
defines that we're in receive mode, if the ISR is triggered the receive functions are called
#define EIB_CHECK_FOR_COLLISION (1<<2)
defined if in transmit mode we have to check if a collision occured
#define START_TX()
start timer: Timer0 using only timer0 to have timer1 and timer2 free for the application
Enumerations
enum etimer_state {
TS_WAITING_CHARS = 0x00, TS_WAITING_TIMEOUT, TS_WAITING_ACK, TS_WAITING_ACK_RESP,
TS_WAITING_BUS_FREE
}
Status for receiving mode, is used in the ISR to decide which function must be called next.
enum etx_state {
TX_NONE = 0x00, TX_SEND_DATA, TX_SEND_CHECKSUM, TX_WAITING_ACK,
TX_ERROR
}
Status for transmitting mode, is used in the ISR to decide which function must be called next.
Functions
static void next_tx_state (enum etx_state new_state)
Set the next state in sending mode.
static void next_rx_state (enum etimer_state new_state)
Set the next state while in receiving mode.
static void freebus_sleep_mode ()
Enter sleep_mode to save power.
static void tx_send_data ()
Generate the telegram checksum and copy the next octet to send to fb_frame.
static void tx_complete ()
Postive acknowledge received, dequeue message.
static void tx_error ()
Negative acknowledge received, check repeat counter and if repeat is not expired resend telegram.
static void fb_putc (const uint8_t c)
Generate an EIB frame and calculate the checksum.
static void timer_rec_chars (void)
A start bit was received in the past now read bit for bit until the end of the octet is received (10 bit).
static void timer_timeout (void)
That function is called if the timeout of 384탎 tiggered.
static void timer_ack (void)
Telegram received completly now decided which telegram type was recieved and if it is necessary to send confirmation back.
static void timer_bus_free (void)
Telegram received.
static void timer_resp_tout (void)
Telegram send completely but ack wasn't received in timerframe, set error flag in control structure.
static void tx_send_checksum ()
Put the checksum in fb_frame and set state machine to wait for ack.
static void tx_wait_ack ()
All data + checksum transmitted, stop IRQ and wait for acknowledge.
static void checkForCollisions ()
Check if we have a collision on the bus and retrigger the timer0 interrupt.
void sendTestTelegram ()
That function can be use to send a test telegramm to the bus, e.g.
uint8_t fbhal_checkProgTaster (void)
Check the programm button and set programming mode and switch LED depending on programming mode.
void fb_send_ack (uint8_t value)
Function to set the ack value for the response to a telegram which must be send in a absolutly excat timing.
void fb_hal_restart (void)
Restart the application by activating the watchdog and block the program.
ISR (INT0_vect)
A falling edge triggers this interrupt.
ISR (TIMER0_COMPA_vect)
The ISR handles which function must be called.
ISR (TIMER0_COMPB_vect)
static void retrigger_tx (void)
Function is called from message queue system to trigger the interrupt for transmitting data.
uint8_t fb_hal_txqueue_msg (struct msg *tx)
Queue message for sending.
void panic (uint8_t reason)
Hold application and set blink code to PORTB pin 0, our prog pin and LED.
void fbhal_Init (void)
Set input/output mode to PORTs, init timers and interrupts.
Variables
static enum etimer_state rx_state
save the next state while be in receiving mode
static enum etx_state tx_state
save the next state while be in transmitting mode
static volatile uint16_t fb_frame
the current octet to transmit, including start, parity and stop bit
static volatile uint16_t rxframe
hold data of the octet while receiving data. That variable is filled bit per bit.
static volatile uint8_t fbstat
the status for transmition (error status, all ok)
static struct msg * rx_ptr
store a recieved telegramm here.
static struct msg * tx_ptr
store telegram which should be sent
static volatile uint8_t fb_ackvalue
if a response byte should be send back set this variable to FB_ACK, FB_NACK, FB_BUSY or FB_NONE
static volatile uint8_t wr_cnt
number of octet in telegram to send
static volatile uint8_t checksum
checksum of the EIB telegram (over all octets)
uint8_t operationMode
defines if sending or receiving data
static volatile uint8_t timer0_skips
counter for skipping timer0 interrupts
Detailed Description
Freebus Hardware Layer. Implementation of a software- uart + timer handling This file consists of function which are bound to the hardware For further information check the pdf 03_02_02 Communication Medium TP 1 v1.0 AS.PDF.
Author:
Dirk Opfer, Matthias Fechner, Christian Bode, Dirk Armbrust
Date:
Fri Oct 26 17:22:16 2007
One bit has the length of 104us (35us date and 69us wait time).
One character is then 11*104us=1144us.
After a character we have a waiting time of 2 bits that means 208us before we start with the next start bit.
When the telgram is complete the ackknowledge is sent after 13 bit wait time that means 13*104us=1352us
After the acknowledge the device have to wait 50 bits that means bus is free after 50*104us=5200us + wait time for priority The wait time for priority depends on the priority and is:
low (4) or high (3): wait 3 bits 3*104us=312us
system (2) or alarm (1): no waiting time
The IACK or INACK has no waiting time and will immediatly be transmitted.
So the waiting time for received mode will be: -EXT INT triggered: Timer0 wait 104탎 for bit 0 -Timer0 wait 104탎 for each next bit (bit 1, 2, 3, 4, 5, 6, 7, P, S) till full character received -Timer0 wait 2*104탎 (wait time between character) = 208탎 and start ACK timer with TIMER0 1352탎, enable EXT INT -Loop the last two steps till we have not received a bit for
If compiled with -DDEBUG_TIMING the 8 IO line are used to output debugging:
PIN8: 1=receive mode, 0=send mode
Receive Mode:
PIN1: 1=start bit received, 0=function left
PIN2: 1=start overflow interrupt, 0=function left
PIN3: 1=read bit (timer_rec_chars), 0=function left
PIN4: 1=read bit information, 0=bit finished
PIN5: 1=timeout reached (timer_timeout), 0=function left
PIN6: 1=sent ACK (timer_ack), 0=function left
PIN7: 1=bus free (timer_bus_free), 0=function left
Send Mode:
PIN1: 1=prepare telegram, 0=function left
PIN2: 1=start overflow interrupt, 0=function left
PIN3: 1=send bit, 0=working on send bit finished
PIN4: 1=check for collision, 0=function left
PIN5: 1=prepare data for ACK, 0=function left
PIN6: 1=waiting for ACK, 0=function left
PIN7: 1=telegram complete, 0=function left
PIN5, PIN6, PIN7: 1=tx_error, repeat telegram, 0=function left
Todo:
Die Timerwerte sollten nochmal nachgerechnet/nachgemessen werden.
Define Documentation
#define EIB_BIT_TIME 104U
duration of one bit on the EIB
Referenced by fbhal_Init(), and ISR().
#define EIB_CHECK_FOR_COLLISION (1<<2)
defined if in transmit mode we have to check if a collision occured
Referenced by checkForCollisions(), and ISR().
#define EIB_NONE_MODE 0
the receive and sending part is in idle mode
Referenced by fbhal_Init().
#define EIB_RECEIVE_MODE (1<<1)
defines that we're in receive mode, if the ISR is triggered the receive functions are called
Referenced by ISR(), tx_complete(), and tx_wait_ack().
#define EIB_SEND_MODE (1<<0)
defines that we're in send mode, if the ISR is triggered the send functions are called
Referenced by ISR(), and tx_send_data().
#define EIB_TX_HIGHTIME EIB_BIT_TIME-EIB_TX_LOWTIME
for the rest of the time the bus is high
#define EIB_TX_LOWTIME 40U
How long we hold the level on that value (35us).
Referenced by fbhal_Init().
#define START_TX ()
Value:
{ \
          DISABLE_RX_INT();                  /* disable INT0 interrupt while sending */ \
          operationMode=EIB_SEND_MODE;       /* set send mode for operation */ \
/*          RELOAD_TIMER0(255,(1<<CS00));  */ \
 \
          TCNT0  = EIB_BIT_TIME-10;          /* TX start after 10탎 */\
          TIFR0  = (1<<OCF0A)|(1<<OCF0B) ;   /* clear pending interrups */ \
          TIMSK0 |= (( 1<<OCIE0A )|( 1<<OCIE0B )); /* enable OCRA, OCRB interrupts */  \
          TCCR0B = (1<<CS01);                /* start the timer */ \
          DEBUG_PIN8_OFF(); }
start timer: Timer0 using only timer0 to have timer1 and timer2 free for the application
Referenced by retrigger_tx(), timer_ack(), and timer_bus_free().
Enumeration Type Documentation
enum etimer_state
Status for receiving mode, is used in the ISR to decide which function must be called next.
Todo:
define a macro for following instructions in freebus-atmegaxxx.h
Enumerator:
TS_WAITING_CHARS
normal operation, waiting for characters
TS_WAITING_TIMEOUT
frame received, waiting for timeout or more data ca. 300탎
TS_WAITING_ACK
data received, time to send ack 1.2ms
TS_WAITING_ACK_RESP
no ack received
TS_WAITING_BUS_FREE
data received, waiting for timeout or more data 5ms
enum etx_state
Status for transmitting mode, is used in the ISR to decide which function must be called next.
Enumerator:
TX_NONE
doing nothing
TX_SEND_DATA
currently sending data
TX_SEND_CHECKSUM
sending checksum
TX_WAITING_ACK
waiting for ACK
TX_ERROR
error in sending data occured
Function Documentation
static void checkForCollisions () [inline, static]
Check if we have a collision on the bus and retrigger the timer0 interrupt.
The function is called after 35탎.
Todo:
implement collition detection
Returns:
Bustiming: Bitzeit fuer High-Pegel (104us - 35us = 69us)
References EIB_CHECK_FOR_COLLISION, FB_COLLISION, fb_frame, fbstat, OFF, operationMode, TIMSK, TX_ERROR, and tx_state.
void fb_hal_restart (void) [inline]
Restart the application by activating the watchdog and block the program.
References ENABLE_WATCHDOG.
Referenced by A_Restart().
uint8_t fb_hal_txqueue_msg (struct msg * tx)
Queue message for sending.
Parameters:
tx Pointer to message
Returns:
References queuemsg(), and retrigger_tx().
Referenced by A_ADC_Read(), A_DeviceDescriptor_Read(), A_Memory_Read(), A_PhysicalAddress_Read(), ncd_resp(), readApplication(), sendExtTelegram(), sendTelegram(), and sendTestTelegram().
static void fb_putc (const uint8_t c) [inline, static]
Generate an EIB frame and calculate the checksum.
The EIB frame is saved in fb_frame.
Parameters:
c The byte to transfer
References fb_frame.
Referenced by timer_ack(), tx_send_checksum(), and tx_send_data().
void fb_send_ack (uint8_t value) [inline]
Function to set the ack value for the response to a telegram which must be send in a absolutly excat timing.
Parameters:
value Ackvalue can be FB_ACK, FB_NACK, FB_BUSY and FB_NONE
References DEBUG_PUTS, FB_ACK, and fb_ackvalue.
Referenced by A_ADC_Read(), A_DeviceDescriptor_Read(), A_GroupValue_Read(), A_GroupValue_Write(), A_Memory_Read(), A_Memory_Write(), A_PhysicalAddress_Read(), A_PhysicalAddress_Write(), Ignore(), T_Connect_Req(), T_Disconnect_Req(), and timer_timeout().
uint8_t fbhal_checkProgTaster (void)
Check the programm button and set programming mode and switch LED depending on programming mode.
Programm button is on PB0 and pin 4 on Freebus connector.
Function detects the state of the prog button (debounced) and sets the programming mode. This is done only every 16th call, because the 킗 needs some time to switch from output to input mode and so we got more negative duty cylce for the prog led.
Bug:
The macro SET_IO_PROG(IO_OUTPUT) could not be used here, because this sets the DDR and also the PORT = 0. This won't work.
Todo:
Check if this function is working fine.
Author:
Matthias Fechner, Tobias Buss
References DEBUG_PUTS, delay, PROG_DDR, PROG_PIN, PROG_PORT, SS_PROG, and systemState.
Referenced by main().
void fbhal_Init (void)
Set input/output mode to PORTs, init timers and interrupts.
Todo:
Timer und Interrupt-Register konfigurieren
Todo:
define a macro for following instructions in freebus-atmegaxxx.h
References CONFIGURE_INT0, EIB_BIT_TIME, EIB_NONE_MODE, EIB_TX_LOWTIME, FB_BUS_FREE, fb_frame, fbstat, IO_INPUT, IO_OUTPUT, next_rx_state(), OFF, operationMode, rxframe, systemState, and TS_WAITING_CHARS.
Referenced by main().
void freebus_sleep_mode () [static]
Enter sleep_mode to save power.
Todo:
write that function.
ISR (TIMER0_COMPA_vect)
The ISR handles which function must be called.
States are defined in the state diagramm.
Returns:
Todo:
timeout depends on the message type, repeat, alarm
References EIB_CHECK_FOR_COLLISION, EIB_RECEIVE_MODE, EIB_SEND_MODE, ENABLE_RX_INT, fb_ackvalue, fb_frame, next_rx_state(), ON, operationMode, rx_state, rxframe, timer0_skips, timer_ack(), timer_bus_free(), timer_rec_chars(), timer_resp_tout(), timer_timeout(), TS_WAITING_ACK, TS_WAITING_ACK_RESP, TS_WAITING_BUS_FREE, TS_WAITING_CHARS, TS_WAITING_TIMEOUT, tx_error(), TX_ERROR, TX_NONE, tx_send_checksum(), TX_SEND_CHECKSUM, tx_send_data(), TX_SEND_DATA, tx_state, tx_wait_ack(), and TX_WAITING_ACK.
ISR (INT0_vect)
A falling edge triggers this interrupt.
It's the start of an EIB telegram. Configure timer0 to read the bits starting with LSB. build frame: Stop Stop Parity 7 6 5 4 3 2 1 0 Start
Returns:
Todo:
define a macro for following instructions in freebus-atmegaxxx.h
References DEBUG_PUTC, EIB_BIT_TIME, EIB_RECEIVE_MODE, FB_BUS_FREE, fbstat, next_rx_state(), operationMode, rxframe, timer0_skips, and TS_WAITING_CHARS.
static void next_rx_state (enum etimer_state new_state) [inline, static]
Set the next state while in receiving mode.
Parameters:
new_state Next function which must be called after timer triggers.
References rx_state.
Referenced by fbhal_Init(), ISR(), timer_ack(), timer_rec_chars(), timer_timeout(), tx_complete(), tx_error(), and tx_wait_ack().
static void next_tx_state (enum etx_state new_state) [inline, static]
Set the next state in sending mode.
Parameters:
new_state Next function which must be called after timer triggers.
References tx_state.
Referenced by tx_send_checksum(), tx_send_data(), and tx_wait_ack().
void panic (uint8_t reason)
Hold application and set blink code to PORTB pin 0, our prog pin and LED.
Todo:
Replace that function with a mechanism that not completely kills the controller application
Parameters:
reason
References IO_OUTPUT, OFF, and ON.
static void retrigger_tx (void) [static]
Function is called from message queue system to trigger the interrupt for transmitting data.
References checksum, FB_BUS_FREE, fbstat, MSG_SENDING, START_TX, msg::state, tx_send_data(), TX_SEND_DATA, tx_state, and wr_cnt.
Referenced by fb_hal_txqueue_msg().
void sendTestTelegram (void)
That function can be use to send a test telegramm to the bus, e.g.
to measure signal levels in circuit.
References AllocMsgI(), fbus_hdr::apci, fbus_hdr::ctrl, msg::data, DEBUG_NEWLINE, DEBUG_PUTS, fbus_hdr::dest, eeprom_ParamRead(), FB_BUS_FREE, fb_hal_txqueue_msg(), fbstat, msg::len, fbus_hdr::npci, PA_ADDRESS_HIGH, PA_ADDRESS_LOW, msg::repeat, fbus_hdr::src, and fbus_hdr::tpci.
Referenced by main().
static void timer_ack (void) [static]
Telegram received completly now decided which telegram type was recieved and if it is necessary to send confirmation back.
If confirmation is requested return (1 octet) else wait 5.xxms which means end of telegram.
Todo:
timeout depends on the message type, repeat, alarm on prio 1&2 wait 5,216ms, on prio 3&4 wait 5,216ms+312탎
References fb_ackvalue, fb_putc(), next_rx_state(), START_TX, timer0_skips, and TS_WAITING_BUS_FREE.
Referenced by ISR().
static void timer_bus_free (void) [static]
Telegram received.
Stop timer
Todo:
define a macro for following instructions in freebus-atmegaxxx.h
References checksum, DEBUG_NEWLINE, DEBUG_PUTC, DEBUG_PUTHEX, FB_BUS_FREE, fbstat, MSG_ALLOC, MSG_SENDING, START_TX, msg::state, tx_complete(), tx_send_data(), TX_SEND_DATA, tx_state, and wr_cnt.
Referenced by ISR().
static void timer_rec_chars (void) [static]
A start bit was received in the past now read bit for bit until the end of the octet is received (10 bit).
Then save the octet and start the timer for the next octet.
References AllocMsgI(), msg::data, DEBUG_NEWLINE, DEBUG_PUTHEX, ENABLE_RX_INT, FB_FRAME_ERR, FB_PARITY_ERR, fbstat, msg::len, next_rx_state(), rxframe, timer0_skips, and TS_WAITING_TIMEOUT.
Referenced by ISR().
static void timer_resp_tout (void) [static]
Telegram send completely but ack wasn't received in timerframe, set error flag in control structure.
References tx_error().
Referenced by ISR().
static void timer_timeout (void) [static]
That function is called if the timeout of 384탎 tiggered.
That means the end of the telegram is reached. Now prepare all for the ack which must be sent within 1.352탎-384탎.
Todo:
goto sollte man immer vermeiden
References msg::data, DEBUG_NEWLINE, DEBUG_PUTS, DISABLE_RX_INT, FB_ACK, fb_ackvalue, FB_FRAME_ERR, fb_handlemsg(), FB_MESSAGE, FB_NACK, FB_PARITY_ERR, fb_send_ack(), fbstat, FreeMsg(), msg::len, MSG_WAIT_ACK, next_rx_state(), msg::state, timer0_skips, TS_WAITING_ACK, tx_complete(), and tx_error().
Referenced by ISR().
static void tx_complete (void) [inline, static]
Postive acknowledge received, dequeue message.
Todo:
: recalculate timer settings for different priorities
Todo:
: recalculate timer settings for different priorities
Todo:
timeout depends on the message type, repeat, alarm
References dequeuemsg(), EIB_RECEIVE_MODE, msg::flags, MSG_COMPLETE, MSG_HI_PRIO, next_rx_state(), operationMode, msg::state, timer0_skips, and TS_WAITING_BUS_FREE.
Referenced by timer_bus_free(), and timer_timeout().
static void tx_error () [static]
Negative acknowledge received, check repeat counter and if repeat is not expired resend telegram.
Set the collision flag.
Todo:
calculate always high prio
Todo:
timeout depends on the message type, repeat, alarm
References msg::data, dequeuemsg(), FB_COLLISION, fbstat, msg::flags, MSG_ALLOC, MSG_COMPLETE, MSG_HI_PRIO, next_rx_state(), msg::repeat, msg::state, timer0_skips, and TS_WAITING_BUS_FREE.
Referenced by ISR(), timer_resp_tout(), and timer_timeout().
static void tx_send_checksum (void) [inline, static]
Put the checksum in fb_frame and set state machine to wait for ack.
References checksum, fb_putc(), next_tx_state(), and TX_WAITING_ACK.
Referenced by ISR().
static void tx_send_data (void) [inline, static]
Generate the telegram checksum and copy the next octet to send to fb_frame.
If the telegramm is finished set state machine to send the checksum.
References checksum, msg::data, EIB_SEND_MODE, fb_putc(), msg::len, next_tx_state(), operationMode, TX_SEND_CHECKSUM, and wr_cnt.
Referenced by ISR(), retrigger_tx(), and timer_bus_free().
static void tx_wait_ack (void) [inline, static]
All data + checksum transmitted, stop IRQ and wait for acknowledge.
References EIB_RECEIVE_MODE, ENABLE_RX_INT, MSG_WAIT_ACK, next_rx_state(), next_tx_state(), operationMode, rxframe, msg::state, timer0_skips, TS_WAITING_ACK_RESP, and TX_NONE.
Referenced by ISR().
Variable Documentation
volatile uint8_t checksum [static]
checksum of the EIB telegram (over all octets)
Referenced by CMessage::CalcChecksum(), fb_handlemsg(), retrigger_tx(), timer_bus_free(), tx_send_checksum(), and tx_send_data().
volatile uint8_t fb_ackvalue [static]
if a response byte should be send back set this variable to FB_ACK, FB_NACK, FB_BUSY or FB_NONE
Referenced by fb_send_ack(), ISR(), timer_ack(), and timer_timeout().
volatile uint16_t fb_frame [static]
the current octet to transmit, including start, parity and stop bit
Referenced by checkForCollisions(), fb_putc(), fbhal_Init(), and ISR().
volatile uint8_t fbstat [static]
the status for transmition (error status, all ok)
Referenced by checkForCollisions(), fbhal_Init(), ISR(), retrigger_tx(), sendTestTelegram(), timer_bus_free(), timer_rec_chars(), timer_timeout(), and tx_error().
uint8_t operationMode
defines if sending or receiving data
Referenced by checkForCollisions(), fbhal_Init(), ISR(), tx_complete(), tx_send_data(), and tx_wait_ack().
struct msg* rx_ptr [static]
store a recieved telegramm here.
enum etimer_state rx_state [static]
save the next state while be in receiving mode
Referenced by ISR(), and next_rx_state().
volatile uint16_t rxframe [static]
hold data of the octet while receiving data. That variable is filled bit per bit.
Referenced by fbhal_Init(), ISR(), timer_rec_chars(), and tx_wait_ack().
volatile uint8_t timer0_skips [static]
counter for skipping timer0 interrupts
Referenced by ISR(), timer_ack(), timer_rec_chars(), timer_timeout(), tx_complete(), tx_error(), and tx_wait_ack().
struct msg* tx_ptr [static]
store telegram which should be sent
enum etx_state tx_state [static]
save the next state while be in transmitting mode
Referenced by checkForCollisions(), ISR(), next_tx_state(), retrigger_tx(), and timer_bus_free().
volatile uint8_t wr_cnt [static]
number of octet in telegram to send
Referenced by retrigger_tx(), timer_bus_free(), and tx_send_data().