FreeBusAVR: include/uart.h File Reference
include/uart.h File Reference
Handles communication via uart (polling mode)
Functions
void uart_init (void)
Set the baudrate and configure the RS232 interface.
void uart_putc (unsigned char c)
Queue a character and start background sending to rs232.
void uart_puts (const char *s)
Display string on rs232.
void uart_hex (unsigned char h)
Queue a character and write it as a hex value to rs232.
void uart_newline (void)
Queue a newline and write it to the rs232.
void uart_putc_blocking (unsigned char c)
Write a character to rs232 without using the queueing system.
void uart_hex_blocking (unsigned char c)
Write a character as hex to rs232 without using the queueing system.
void uart_puts_blocking (const char *s)
Write a string to the rs232 without using the queueing system.
void uart_newline_blocking (void)
Write a newline to rs232 without using the queueing system.
void uart_put (unsigned char *dat, unsigned char len)
Write the given binary data to rs232 using the queueing system.
Detailed Description
Handles communication via uart (polling mode)
Author:
Dirk Opfer, Matthias Fechner
Date:
Fri Oct 26 17:18:15 2007
Function Documentation
void uart_hex (unsigned char h)
Queue a character and write it as a hex value to rs232.
Parameters:
h Character to write as hex value
References uart_putc().
void uart_hex_blocking (unsigned char h)
Write a character as hex to rs232 without using the queueing system.
Parameters:
h
References uart_putc_blocking().
void uart_init (void)
Set the baudrate and configure the RS232 interface.
void uart_newline (void)
Queue a newline and write it to the rs232.
References uart_putc().
void uart_newline_blocking (void)
Write a newline to rs232 without using the queueing system.
References uart_putc_blocking().
void uart_put (unsigned char * dat, unsigned char len)
Write the given binary data to rs232 using the queueing system.
References AllocMsg(), uart_cmds::count, uart_cmds::data, msg::data, uart_cmds::offset, queuemsg(), and trigger_uart().
void uart_putc (unsigned char c)
Queue a character and start background sending to rs232.
Parameters:
c
References AllocMsg(), AppendToQueue(), uart_cmds::count, uart_cmds::data, msg::data, DISABLE_IRQS, ENABLE_IRQS, uart_cmds::offset, queuemsg(), and trigger_uart().
Referenced by uart_hex(), uart_newline(), and uart_puts().
void uart_putc_blocking (unsigned char c)
Write a character to rs232 without using the queueing system.
Parameters:
c
Referenced by uart_hex_blocking(), uart_newline_blocking(), and uart_puts_blocking().
void uart_puts (const char * s)
Display string on rs232.
The strings are saved on flash and not in sram. See here definition of DEBUG_PUTS on freebus-debug.h.
Parameters:
s String pointer which points to flash
References uart_putc().
void uart_puts_blocking (const char * s)
Write a string to the rs232 without using the queueing system.
Parameters:
s
References uart_putc_blocking().