FreeBusAVR: include/lcd-lib.h File Reference
include/lcd-lib.h File Reference
#include "delay.h"
Defines
#define LCD_DATA_PORT PORTD
on which port the LCD data pin is connected
#define LCD_CLOCK_PORT PORTD
on which port the LCD clock port is connected
#define LCD_E_PORT PORTD
on which port the LCD e pin is connected
#define LCD_PIN_DATA 5
on which port number is the data pin connected
#define LCD_PIN_CLOCK 6
on which port number is the clock pin connected
#define LCD_PIN_E 7
on which port number is the e pin connected
#define LCD_ON 0x0C
switch LCD on
#define LCD_OFF 0x08
switch LCD off
#define LCD_CURSOR_ON 0x0A
switch cursor on LCD on
#define LCD_CURSOR_OFF 0x08
switch cursor on LCD off
#define LCD_CURSOR_BLINK 0x09
set cursor to blink mode
#define LCD_CURSOR_NOBLINK 0x08
disable blink mode of cursor
#define LCD_CLEAR 0x01
clear the LCD
#define LCD_HOME 0x02
jump to home position on LCD
#define DDROFPORT(X) (*(&X - 1))
macro used to switch port direction
Functions
void lcd_init (unsigned char cmd)
Init the LCD.
void lcd_controller_init (unsigned char cmd)
Init the controller.
void lcd_write_global (unsigned char byte, unsigned int)
Function which is called for all write proceses.
void lcd_puts (const char *s)
Write a string to the LCD.
void lcd_putc (char c)
Display a single character on the LCD.
void lcd_newline (void)
Display a newline on the LCD display.
void lcd_digit (uint8_t d)
Display a character as digit.
void lcd_hex (uint8_t d)
Display a char as hex.
Detailed Description
Author:
Matthias Fechner <idefix@fechner.net>
Date:
Mon Nov 26 22:41:50 2007
Define Documentation
#define DDROFPORT (X) (*(&X - 1))
macro used to switch port direction
Referenced by lcd_init().
#define LCD_CLEAR 0x01
clear the LCD
Referenced by lcd_controller_init().
#define LCD_CLOCK_PORT PORTD
on which port the LCD clock port is connected
Referenced by lcd_init().
#define LCD_CURSOR_BLINK 0x09
set cursor to blink mode
Referenced by lcd_controller_init().
#define LCD_CURSOR_NOBLINK 0x08
disable blink mode of cursor
#define LCD_CURSOR_OFF 0x08
switch cursor on LCD off
#define LCD_CURSOR_ON 0x0A
switch cursor on LCD on
Referenced by lcd_controller_init().
#define LCD_DATA_PORT PORTD
on which port the LCD data pin is connected
Referenced by lcd_init().
#define LCD_E_PORT PORTD
on which port the LCD e pin is connected
Referenced by lcd_init().
#define LCD_HOME 0x02
jump to home position on LCD
Referenced by lcd_controller_init().
#define LCD_OFF 0x08
switch LCD off
#define LCD_ON 0x0C
switch LCD on
Referenced by lcd_controller_init().
#define LCD_PIN_CLOCK 6
on which port number is the clock pin connected
Referenced by lcd_init().
#define LCD_PIN_DATA 5
on which port number is the data pin connected
Referenced by lcd_init().
#define LCD_PIN_E 7
on which port number is the e pin connected
Referenced by lcd_init().
Function Documentation
void lcd_controller_init (unsigned char cmd)
Init the controller.
At 8MHz function needs 65436.75 us to execute.
Parameters:
cmd
References delay, LCD_CLEAR, lcd_command, LCD_CURSOR_BLINK, LCD_CURSOR_ON, LCD_HOME, and LCD_ON.
Referenced by lcd_init().
void lcd_digit (uint8_t d)
Display a character as digit.
Parameters:
d
References lcd_putc().
void lcd_hex (uint8_t d)
Display a char as hex.
Function needs 146.13us
Parameters:
d
References lcd_putc().
void lcd_init (unsigned char cmd)
Init the LCD.
Parameters:
cmd Command which should be send after initialisation is finished.
References DDROFPORT, delay, LCD_CLOCK_PORT, lcd_controller_init(), LCD_DATA_PORT, LCD_E_PORT, LCD_PIN_CLOCK, LCD_PIN_DATA, and LCD_PIN_E.
void lcd_newline (void)
Display a newline on the LCD display.
Todo:
function should be implemented
void lcd_putc (char c)
Display a single character on the LCD.
Function needs 71.38us to execute.
Parameters:
c
References delay, and lcd_write.
Referenced by lcd_digit(), lcd_hex(), and lcd_puts().
void lcd_puts (const char * s)
Write a string to the LCD.
Parameters:
s
References lcd_putc().
void lcd_write_global (unsigned char byte, unsigned int command)
Function which is called for all write proceses.
Parameters:
byte the byte which should be send
command 0 -> send command, 1 -> send text
References lcd_clock_high, lcd_clock_low, lcd_data_high, lcd_data_low, and lcd_toggle_e().