FreeBusAVR: lib/lcd-lib.c File Reference
lib/lcd-lib.c File Reference
Lib to control a 4x20 character display with 3 wires the current file works only with 8Bit mode with 3 wires and a bit shifter called 74HC164N. It is only included if -DDEBUG_LCD is set at compile time.
#include <avr/io.h>
#include "lcd-lib.h"
Defines
#define LCD_MODE_SERIAL_8BIT
LCD is connected in 8-bit mode with a 74HC164N bit shifter.
#define lcd_e_delay() __asm__ __volatile__("rjmp 1f\n 1:")
delay which must be used between enable e and disable e pin
#define lcd_e_high() LCD_E_PORT |= (1<<LCD_PIN_E)
enable the e pin to write values to LCD
#define lcd_e_low() LCD_E_PORT &= ~(1<<LCD_PIN_E)
disable the e pin, LCD is not reading from data pins
#define lcd_data_high() LCD_DATA_PORT |= (1<<LCD_PIN_DATA)
enable data pin
#define lcd_data_low() LCD_DATA_PORT &= ~(1<<LCD_PIN_DATA)
disable data pin
#define lcd_clock_high() LCD_CLOCK_PORT |= (1<<LCD_PIN_CLOCK)
enable clock pin
#define lcd_clock_low() LCD_CLOCK_PORT &= ~(1<<LCD_PIN_CLOCK)
disable clock pin
#define lcd_command(X) lcd_write_global((X),0)
map lcd_command function to a global write function
#define lcd_write(X) lcd_write_global((X),1)
map lcd_write function to a global write function
Functions
static void lcd_toggle_e (void)
Toggle the E (enable) pin to read data which is on the IO pins on the LCD.
void lcd_init (unsigned char cmd)
Init the LCD.
void lcd_controller_init (unsigned char cmd)
Init the controller.
void lcd_write_global (unsigned char byte, unsigned int command)
Function which is called for all write proceses.
void lcd_puts (const char *s)
Write a string to the LCD.
void lcd_putc (char c)
Display a single character on the LCD.
void lcd_newline ()
Display a newline on the LCD display.
void lcd_digit (uint8_t d)
Display a character as digit.
void lcd_hex (uint8_t d)
Display a char as hex.
Detailed Description
Lib to control a 4x20 character display with 3 wires the current file works only with 8Bit mode with 3 wires and a bit shifter called 74HC164N. It is only included if -DDEBUG_LCD is set at compile time.
Author:
Matthias Fechner <idefix@fechner.net>
Date:
Mon Nov 26 22:31:50 2007
Define Documentation
#define lcd_clock_high () LCD_CLOCK_PORT |= (1<<LCD_PIN_CLOCK)
enable clock pin
Referenced by lcd_write_global().
#define lcd_clock_low () LCD_CLOCK_PORT &= ~(1<<LCD_PIN_CLOCK)
disable clock pin
Referenced by lcd_write_global().
#define lcd_command (X) lcd_write_global((X),0)
map lcd_command function to a global write function
Referenced by lcd_controller_init().
#define lcd_data_high () LCD_DATA_PORT |= (1<<LCD_PIN_DATA)
enable data pin
Referenced by lcd_write_global().
#define lcd_data_low () LCD_DATA_PORT &= ~(1<<LCD_PIN_DATA)
disable data pin
Referenced by lcd_write_global().
#define lcd_e_delay () __asm__ __volatile__("rjmp 1f\n 1:")
delay which must be used between enable e and disable e pin
Referenced by lcd_toggle_e().
#define lcd_e_high () LCD_E_PORT |= (1<<LCD_PIN_E)
enable the e pin to write values to LCD
Referenced by lcd_toggle_e().
#define lcd_e_low () LCD_E_PORT &= ~(1<<LCD_PIN_E)
disable the e pin, LCD is not reading from data pins
Referenced by lcd_toggle_e().
#define LCD_MODE_SERIAL_8BIT
LCD is connected in 8-bit mode with a 74HC164N bit shifter.
LCD is connected in 4-bit mode with a 74HC164N bit shifter LCD is connected in 8-bit mode LCD is connected in 4-bit mode
#define lcd_write (X) lcd_write_global((X),1)
map lcd_write function to a global write function
Referenced by lcd_putc().
Function Documentation
void lcd_controller_init (unsigned char cmd)
Init the controller.
At 8MHz function needs 65436.75 us to execute.
Parameters:
cmd
References delay, LCD_CLEAR, lcd_command, LCD_CURSOR_BLINK, LCD_CURSOR_ON, LCD_HOME, and LCD_ON.
Referenced by lcd_init().
void lcd_digit (uint8_t d)
Display a character as digit.
Parameters:
d
References lcd_putc().
void lcd_hex (uint8_t d)
Display a char as hex.
Function needs 146.13us
Parameters:
d
References lcd_putc().
void lcd_init (unsigned char cmd)
Init the LCD.
Parameters:
cmd Command which should be send after initialisation is finished.
References DDROFPORT, delay, LCD_CLOCK_PORT, lcd_controller_init(), LCD_DATA_PORT, LCD_E_PORT, LCD_PIN_CLOCK, LCD_PIN_DATA, and LCD_PIN_E.
void lcd_newline (void)
Display a newline on the LCD display.
Todo:
function should be implemented
void lcd_putc (char c)
Display a single character on the LCD.
Function needs 71.38us to execute.
Parameters:
c
References delay, and lcd_write.
Referenced by lcd_digit(), lcd_hex(), and lcd_puts().
void lcd_puts (const char * s)
Write a string to the LCD.
Parameters:
s
References lcd_putc().
static void lcd_toggle_e (void) [static]
Toggle the E (enable) pin to read data which is on the IO pins on the LCD.
References lcd_e_delay, lcd_e_high, and lcd_e_low.
Referenced by lcd_write_global().
void lcd_write_global (unsigned char byte, unsigned int command)
Function which is called for all write proceses.
Parameters:
byte the byte which should be send
command 0 -> send command, 1 -> send text
References lcd_clock_high, lcd_clock_low, lcd_data_high, lcd_data_low, and lcd_toggle_e().