FreeBusAVR: lib/uart.c File Reference
lib/uart.c File Reference
Handles communication via uart (polling mode). Is only included if compiled with -DDEBUG_UART.
#include <msg_queue.h>
#include <freebus-debug.h>
#include <fb_hardware.h>
Data Structures
struct uart_cmds
Data is written in background to not block other operations, data and control bytes are stored in that structure.
Defines
#define FF_CLOCK 8000000L
use here own variable because avr studio always set F_CPU to 8000000UL so calculation will fail
#define BAUD 38400L
baud rate, the L at the end is important, DO NOT use UL!
#define UBRR_VAL ((FF_CLOCK+BAUD*8)/(BAUD*16)-1)
round clever
#define BAUD_REAL (FF_CLOCK/(16*(UBRR_VAL+1)))
real baud rate
#define BAUD_ERROR ((BAUD_REAL*1000)/BAUD-1000)
error rate in promile
#define DEBUG_MSG_MAX_LEN MSG_MAX_DATA_LENGTH-2
max length a debug message can have
Functions
uint8_t AppendToQueue (struct msg *current, uint8_t length, uint8_t *character)
Take the given char and append it to a debug message queue or allocate a new message container and store it there.
void uart_init ()
Set the baudrate and configure the RS232 interface.
ISR (SIG_UART_TRANS)
ISR is called if rs232 is empty and can store the next byte.
static void trigger_uart (void)
Start the send progress and write all queued data to rs232 interface.
void uart_putc_blocking (unsigned char c)
Write a character to rs232 without using the queueing system.
void uart_puts_blocking (const char *s)
Write a string to the rs232 without using the queueing system.
void uart_hex_blocking (unsigned char h)
Write a character as hex to rs232 without using the queueing system.
void uart_newline_blocking ()
Write a newline to rs232 without using the queueing system.
void uart_putc (unsigned char c)
Queue a character and start background sending to rs232.
void uart_puts (const char *s)
Display string on rs232.
void uart_hex (unsigned char h)
Queue a character and write it as a hex value to rs232.
void uart_newline ()
Queue a newline and write it to the rs232.
Variables
static const uint8_t pgmhex[] PROGMEM = {'0', '1','2','3','4','5','6','7','8','9','A','B','C','D','E','F' }
used to display hexvalues
static struct msg * uart_msg
queue for debug messages
Detailed Description
Handles communication via uart (polling mode). Is only included if compiled with -DDEBUG_UART.
Author:
Dirk Opfer, Matthias Fechner
Date:
Fri Oct 26 17:18:15 2007
Define Documentation
#define BAUD 38400L
baud rate, the L at the end is important, DO NOT use UL!
#define BAUD_ERROR ((BAUD_REAL*1000)/BAUD-1000)
error rate in promile
#define BAUD_REAL (FF_CLOCK/(16*(UBRR_VAL+1)))
real baud rate
#define DEBUG_MSG_MAX_LEN MSG_MAX_DATA_LENGTH-2
max length a debug message can have
Referenced by AppendToQueue().
#define FF_CLOCK 8000000L
use here own variable because avr studio always set F_CPU to 8000000UL so calculation will fail
#define UBRR_VAL ((FF_CLOCK+BAUD*8)/(BAUD*16)-1)
round clever
Referenced by uart_init().
Function Documentation
uint8_t AppendToQueue (struct msg * current, uint8_t length, uint8_t * character)
Take the given char and append it to a debug message queue or allocate a new message container and store it there.
That function was written to use the memory for debugging message more efficient.
Parameters:
current Pointer to the message queue
length Length of characters to append to the message queue
character Pointer to characters to store in the message queue
Returns:
References uart_cmds::count, uart_cmds::data, msg::data, DEBUG_MSG_MAX_LEN, DISABLE_IRQS, ENABLE_IRQS, MSG_ALLOC, MSG_SENDING, msg::next, uart_cmds::offset, and msg::state.
Referenced by uart_putc().
ISR (SIG_UART_TRANS)
ISR is called if rs232 is empty and can store the next byte.
Returns:
References uart_cmds::count, uart_cmds::data, msg::data, dequeuemsg(), DISABLE_UART_TX_IRQ, uart_cmds::offset, and UART_SEND_BYTE.
static void trigger_uart (void) [inline, static]
Start the send progress and write all queued data to rs232 interface.
Trigger here the first byte and enable ISQ for sending.
References uart_cmds::data, msg::data, ENABLE_UART_TX_IRQ, MSG_ALLOC, MSG_SENDING, uart_cmds::offset, msg::state, and UART_SEND_BYTE.
Referenced by uart_putc().
void uart_hex (unsigned char h)
Queue a character and write it as a hex value to rs232.
Parameters:
h Character to write as hex value
References uart_putc().
void uart_hex_blocking (unsigned char h)
Write a character as hex to rs232 without using the queueing system.
Parameters:
h
References uart_putc_blocking().
void uart_init (void)
Set the baudrate and configure the RS232 interface.
References UBRR_VAL.
void uart_newline (void)
Queue a newline and write it to the rs232.
References uart_putc().
void uart_newline_blocking (void)
Write a newline to rs232 without using the queueing system.
References uart_putc_blocking().
void uart_putc (unsigned char c)
Queue a character and start background sending to rs232.
Parameters:
c
References AllocMsg(), AppendToQueue(), uart_cmds::count, uart_cmds::data, msg::data, uart_cmds::offset, queuemsg(), and trigger_uart().
Referenced by uart_hex(), uart_newline(), and uart_puts().
void uart_putc_blocking (unsigned char c)
Write a character to rs232 without using the queueing system.
Parameters:
c
Referenced by uart_hex_blocking(), uart_newline_blocking(), and uart_puts_blocking().
void uart_puts (const char * s)
Display string on rs232.
The strings are saved on flash and not in sram. See here definition of DEBUG_PUTS on freebus-debug.h.
Parameters:
s String pointer which points to flash
References uart_putc().
void uart_puts_blocking (const char * s)
Write a string to the rs232 without using the queueing system.
Parameters:
s
References uart_putc_blocking().
Variable Documentation
const uint8_t pgmhex [] PROGMEM = {'0', '1','2','3','4','5','6','7','8','9','A','B','C','D','E','F' } [static]
used to display hexvalues
struct msg* uart_msg [static]
queue for debug messages