FreeBusAVR: lib/msg_queue.c File Reference
lib/msg_queue.c File Reference
Management of messagequeues.
#include "fb.h"
#include "fb_hardware.h"
#include "fb_hal.h"
#include "msg_queue.h"
Defines
#define MSG_POOL_SIZE 18
the maximum number of messages which can be stored
Functions
struct msg * AllocMsgI (void)
Allocate space for a message and return a pointer to it.
void queuemsg (struct msg **ptr, struct msg *pmsg, void(*trigger)(void))
Add a new message to the message queue.
void dequeuemsg (struct msg **ptr)
Remove a message from the queue.
void msg_queue_init (void)
Init the message queue system and save default values.
Variables
struct msg msg_pool [MSG_POOL_SIZE]
The message queue which will be used for all message types.
Detailed Description
Management of messagequeues.
Author:
Dirk Opfer
Date:
Mon Oct 29 20:01:34 2007
Define Documentation
#define MSG_POOL_SIZE 18
the maximum number of messages which can be stored
Function Documentation
struct msg* AllocMsgI (void) [read]
Allocate space for a message and return a pointer to it.
Function will call panic(PANIC_NO_MSG) if no more space for messages is left.
Returns:
Pointer to the msg* struct
References COUNT_ARRAY_ELEMENTS, msg::flags, msg::len, MSG_ALLOC, MSG_AUTOFREE, MSG_FREE, msg_pool, msg::next, panic(), PANIC_NO_MSG, and msg::state.
Referenced by AllocMsg(), fb_new_msg(), readApplication(), sendExtTelegram(), sendTelegram(), sendTestTelegram(), and timer_rec_chars().
void dequeuemsg (struct msg ** ptr)
Remove a message from the queue.
Parameters:
ptr Pointer to the message which should be removed.
References DISABLE_IRQS, ENABLE_IRQS, msg::flags, FreeMsg(), MSG_AUTOFREE, and msg::next.
Referenced by ISR(), tx_complete(), and tx_error().
void msg_queue_init (void)
Init the message queue system and save default values.
References COUNT_ARRAY_ELEMENTS, MSG_FREE, msg_pool, and msg::state.
Referenced by main().
void queuemsg (struct msg ** ptr, struct msg * pmsg, void(*)(void) trigger)
Add a new message to the message queue.
Parameters:
ptr
pmsg
trigger
References DISABLE_IRQS, ENABLE_IRQS, and msg::next.
Referenced by eeprom_ParamWrite(), fb_hal_txqueue_msg(), and uart_putc().
Variable Documentation
struct msg msg_pool[MSG_POOL_SIZE]
The message queue which will be used for all message types.
Referenced by AllocMsgI(), and msg_queue_init().