FreeBusAVR: include/msg_queue.h File Reference
include/msg_queue.h File Reference
Definitions for the message queue system used for telegrams and communucation like debugging (also rs232 communication).
#include "fb_hardware.h"
#include <stdlib.h>
#include <stdbool.h>
#include <fb.h>
Data Structures
struct msg
Container that store messages.
Defines
#define MSG_EXT extern
Set MSG_EXT to extern to make clear it is include from an external source like a lib.
#define MSG_MAX_DATA_LENGTH 25
Max length of a message.
#define MSG_AUTOFREE (1<<0)
clear message from queue automatically after successfully handled
#define MSG_HI_PRIO (1<<1)
used for eib message priority handling
#define COUNT_ARRAY_ELEMENTS(x) (sizeof(x)/sizeof(x[0]))
Return the number of elements in an array.
Enumerations
enum emsg_state {
MSG_FREE = 0x00, MSG_ALLOC, MSG_SENDING, MSG_WAIT_ACK,
MSG_COMPLETE
}
Status of the message.
Functions
MSG_EXT void msg_queue_init (void)
Init the message queue system and save default values.
MSG_EXT struct msg * AllocMsgI (void)
Allocate space for a message and return a pointer to it.
MSG_EXT void dequeuemsg (struct msg **ptr)
Remove a message from the queue.
MSG_EXT void queuemsg (struct msg **ptr, struct msg *pmsg, void(*trigger)(void))
Add a new message to the message queue.
static void FreeMsg (struct msg *pmsg)
Free the message and mark it as MSG_FREE.
static struct msg * AllocMsg (void)
Allocate a new message.
static uint8_t isQueueEmpty (struct msg **ptr)
Checks if the given msgqueue is empty No need to disable IRQs.
Detailed Description
Definitions for the message queue system used for telegrams and communucation like debugging (also rs232 communication).
Author:
Dirk Opfer, Matthias Fechner, Christian Bode, Dirk Armbrust
Date:
Sat Apr 05 23:39:28 2008
Define Documentation
#define COUNT_ARRAY_ELEMENTS (x) (sizeof(x)/sizeof(x[0]))
Return the number of elements in an array.
Referenced by fbprot_msg_handler().
#define MSG_AUTOFREE (1<<0)
clear message from queue automatically after successfully handled
Referenced by AllocMsgI(), dequeuemsg(), and fbprot_msg_handler().
#define MSG_EXT extern
Set MSG_EXT to extern to make clear it is include from an external source like a lib.
#define MSG_HI_PRIO (1<<1)
used for eib message priority handling
#define MSG_MAX_DATA_LENGTH 25
Max length of a message.
Enumeration Type Documentation
enum emsg_state
Status of the message.
Enumerator:
MSG_FREE
message is not used and can be allocated
MSG_ALLOC
message parameters are initialized and the message container can store data now
MSG_SENDING
message is marked as sending
MSG_WAIT_ACK
message wait for ack
MSG_COMPLETE
transmittion completed
Function Documentation
static struct msg* AllocMsg (void) [static, read]
Allocate a new message.
Disables IRQs to prevent interrupt while allocating message here.
Returns:
References AllocMsgI(), DISABLE_IRQS, and ENABLE_IRQS.
Referenced by mem_WriteBlock(), uart_put(), and uart_putc().
MSG_EXT struct msg* AllocMsgI (void) [read]
Allocate space for a message and return a pointer to it.
Function will call panic(PANIC_NO_MSG) if no more space for messages is left.
Returns:
Pointer to the msg* struct
References msg::flags, msg::len, MSG_ALLOC, MSG_AUTOFREE, msg::next, and msg::state.
Referenced by AllocMsg(), fb_new_msg(), readApplication(), sendExtTelegram(), and sendTelegram().
MSG_EXT void dequeuemsg (struct msg ** ptr)
Remove a message from the queue.
Parameters:
ptr Pointer to the message which should be removed.
References DISABLE_IRQS, ENABLE_IRQS, msg::flags, FreeMsg(), MSG_AUTOFREE, and msg::next.
Referenced by fbprot_msg_handler(), and ISR().
static void FreeMsg (struct msg * pmsg) [inline, static]
Free the message and mark it as MSG_FREE.
Parameters:
pmsg Pointer to msg which must be marked as free.
Referenced by dequeuemsg(), and fbprot_msg_handler().
static uint8_t isQueueEmpty (struct msg ** ptr) [inline, static]
Checks if the given msgqueue is empty No need to disable IRQs.
Can be called at every context
Parameters:
msgqueue to be checked
References FALSE, and TRUE.
MSG_EXT void msg_queue_init (void)
Init the message queue system and save default values.
Referenced by main().
MSG_EXT void queuemsg (struct msg ** ptr, struct msg * pmsg, void(*)(void) trigger)
Add a new message to the message queue.
Parameters:
ptr
pmsg
trigger
References DISABLE_IRQS, ENABLE_IRQS, and msg::next.
Referenced by fb_hal_txqueue_msg(), fb_handlemsg(), mem_WriteBlock(), uart_put(), and uart_putc().